### ISSUE TITLE
LW2 devices are missing

### ISSUE THREAD

**Issue by cagriy** [bigbadblunt/homeassistant-lightwave2#10]
Switches are successfully added to Home Assistant, they are listed under Configuration > Entity Registry and available on Overview screen. If I toggle switches on Overview screen controls work as expected.

However none of the LW2 switches appear under Configuration > Devices. And I guess because of this there is no way to target an LW2 device in automations.

Am I missing something obvious or is this a limitation of this library ? I am trying to trigger a LW2 switch through automations, is there another way of doing it without targeting it as a device ?

Versions
Home Assistant: 0.101.3
homeassistant-lightwave2 : Current master

**Comment by bigbadblunt** [comment]
You'll need to use a "call service" automation. Below is an example of one that I use.

![image](https://user-images.githubusercontent.com/29158690/69129451-482d5200-0aa6-11ea-9e0c-74f4c5214c3c.png)

**Comment by bigbadblunt** [comment]
Just for completeness, here's the same thing as yaml from automations.yaml

`  action:
  - data:
      entity_id: light.peter_bedroom
    service: light.turn_off
  - data:
      entity_id: light.spotlights
    service: light.turn_off`

**Comment by cagriy** [comment]
It works :) Many thanks.
