### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by SGXander** [bigbadblunt/homeassistant-lightwave2#105]
As of this morning (after updating to 2022.11.3 last night but restarting 3 times after) the integration fails to load with the below messages:

Logger: homeassistant.config_entries
Source: custom_components/lightwave2/__init__.py:84
Integration: Lightwave v2 (Smart Series) custom component ([documentation](https://github.com/bigbadblunt/homeassistant-lightwave2))
First occurred: 08:23:54 (1 occurrences)
Last logged: 08:23:54
Error setting up entry ****@**.** for lightwave2

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/lightwave2/__init__.py", line 84, in async_setup_entry
    await link.async_get_hierarchy()
  File "/usr/local/lib/python3.10/site-packages/lightwave2/lightwave2.py", line 229, in async_get_hierarchy
    await self.async_update_featureset_states()
  File "/usr/local/lib/python3.10/site-packages/lightwave2/lightwave2.py", line 275, in async_update_featureset_states
    _LOGGER.warning("update_featureset_states: failed to read feature ({}), returned {}".format(x.features[y][0], value))
KeyError: <lightwave2.lightwave2.LWRFFeature object at 0x7fee48daa410>

 Logger: lightwave2.lightwave2
Source: runner.py:119
First occurred: 08:23:54 (2 occurrences)
Last logged: 08:23:54
consumer_handler: Received unhandled message: {'version': 1, 'senderId': '1.ip=10=192=22=9*eu=west=1*compute*internal=38346', 'direction': 'response', 'source': '_channel', 'items': [{'itemId': 3, 'success': False, 'error': {'source': 'server', 'group': 17, 'code': 404, 'message': 'dispatcher: destination not connected'}}], 'class': 'feature', 'operation': 'read', 'transactionId': 3}

**Comment by jjl109** [comment]
I think there was actually a Lightwave outage this morning as my official Lightwave app wasn't working either. It didn't show any errors but the loading spinner would spin for a few seconds and then the state of the devices shown was not correct, they were showing as they were last time the app was working.

**Comment by jjl109** [comment]
Outage still ongoing it seems, the web UI is throwing an error.

**Comment by SGXander** [comment]
Seems like it was indeed a big outage. Nice to know the maintenance window the other week was worth it!

**Comment by jjl109** [comment]
Indeed 🤦🏻‍♂️
I wish there was a "service status" page for Lightwave.

**Comment by SGXander** [comment]
I've been really unimpressed with them lately. replacing the energy monitor with hildebrand and the thermostat with a custom shelly setup has only reinforced my issues with them prioritising proprietary over function so I'm in the market for sockets and dimmers that are fully local and HA compatible now.
in the meantime I need to figure out homekit on an IOT vlan so I can locally control the lightwave stuff...

**Comment by SGXander** [comment]
Same again as of an hour ago. Anyone else seeing this?

**Comment by RS-Dog** [comment]
> Same again as of an hour ago. Anyone else seeing this?

Yes mine has bailed this afternoon too. 
getting seriously fed up with them considering how much I’ve paid out to them over the years

**Comment by mkrus** [comment]
Down a few days ago. Then back. Then down again for the last few hours. 

Works from the official app though.

**Comment by SGXander** [comment]
> Down a few days ago. Then back. Then down again for the last few hours. 
> 
> Works from the official app though.

Think it's intermittent.after about 10 restarts HA could control mine but alexa couldn't.

**Comment by Whizzykid** [comment]
I'm not sure if this is related, but my multi clicks are not working. It's been happening over the last few days, but for example, earlier today I could listen to the lightwave2.click event with no problem and the automations I've created worked perfectly. But only an hour later (with no changes) nothing is returned when listening to the event. using the latest beta(3) with homekit hidden and not using the public API

**Comment by bigbadblunt** [comment]
Is this related to #69? For a while now, Lightwave has stopped sending updates after some (unpredictable) time. There is an option to forcibly disconnect and reconnect periodically. This isn't perfect, but seems workable. In the thread for #69 there are some more involved workarounds to detect the failure of updates and perform a reconnect.

**Comment by bigbadblunt** [comment]
I think this one is now resolved, let me know if not.
