### ISSUE TITLE
Status not updating in HA

### ISSUE THREAD

**Issue by fostersimp** [bigbadblunt/homeassistant-lightwave2#107]
Hi,

I can control all of my lights through HA, without any issues.

The problem is after 5 mins, if I turn a light on or off physically (pushing the button/switch on the wall) or turn it on or off through the Lightwave app on my phone.  The status of the light home assistant is not updated. However, it is still possible for me to control the lights through HA.

If I restart HA, then the status of the light update almost immediately after physically pushing the button/switch, again after around 5 mins the status is no longer updating.

**Comment by xela1** [comment]
Is this the same as #69 this is a lightwave issue and not something the addon can resolve, the are workarounds listed in the thread though

**Comment by fostersimp** [comment]
Hi, Yes it is the same! Please delete or close this, as it is a duplication.
