### ISSUE TITLE
Not showing as dimmable bulb in Google Home

### ISSUE THREAD

**Issue by totalitarian** [bigbadblunt/homeassistant-lightwave2#11]
Hi, I have a gen 2 light switch. It work perfectly in Hassio but for some reason it don't show as dimmable in Google Home, it just has the on / off control.

Any ideas?

**Comment by bigbadblunt** [comment]
No, sorry. Mine show up fine in Google Home and are dimmable.

**Comment by totalitarian** [comment]
Re-added them and they now show as dimmable, thanks.
