### ISSUE TITLE
General sign in problem

### ISSUE THREAD

**Issue by obot101** [bigbadblunt/homeassistant-lightwave2#110]
Try to sign in it said it has created a configuration under my email but does not discover any devices. It has been working for the past 3 months. Here is the error: 

WARNING (MainThread) [lightwave2.lightwave2] get_access_token_username: Authentication failed - if network is ok, possible wrong username/password

I have test the email and password in app multiple times any way to fix this?

**Comment by astirling01** [comment]
Same....Nothing is working now for me :(

**Comment by cpdowsett** [comment]
Its good to know that is not just me. I have been unable to sign in since late last night. Looks like its Light wave's problem as i also have no way of logging it on my pc. 
So probably best to change nothing and site tight!

**Comment by swampylee** [comment]
Exactly the same here. Just making a note of it so others on the hunt for this issue realise it's likely to be a Lightwave issue. I've also entered a ticket with them.

**Comment by astirling01** [comment]
I’ve no issue signing into the Lightwave app. Or using the Alexa integration. On 4 Feb 2023, at 13:56, swampylee ***@***.***> wrote:﻿
Exactly the same here. Just making a note of it so others on the hunt for this issue realise it's likely to be a Lightwave issue. I've also entered a ticket with them.

**Comment by swampylee** [comment]
> I’ve no issue signing into the Lightwave app. Or using the Alexa integration. On 4 Feb 2023, at 13:56, swampylee ***@***.***> wrote:﻿ Exactly the same here. Just making a note of it so others on the hunt for this issue realise it's likely to be a Lightwave issue. I've also entered a ticket with them. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

I agree it's not everything. I can log in to the iOS app (although I haven't tried logging out and back in) and I can control through Google Home. I just went on to https://manager.lightwaverf.com/ and changed my password, removed the integration from HA, restarted HA, re-added the integration with the updated password and still see the same issue. So I guess it could be this integration since we probably all upgraded to 2023.2........

**Comment by cpdowsett** [comment]
True 
I have tried going back a version and its still not playing ball

**Comment by swampylee** [comment]
Sorry, another update. Just logged out of the iOS app and I can't log back in with either the old or the new password so to me it's looking like a LightwaveRF issue.

**Comment by cpdowsett** [comment]
LOL 
Was about to risk logging out. Thanks for taking that one for the team.

**Comment by M0WGF** [comment]
Looks to be lightwave are having authentication problems as I can't even login through their website.

**Comment by astirling01** [comment]
Repeatedly hiding the sign in button on the web control panel actually gets me in. No joy with home assistant thoughOn 4 Feb 2023, at 16:06, M0WGF ***@***.***> wrote:﻿
Looks to be lightwave are having authentication problems as I can't even login through their website.

**Comment by RGarrett93** [comment]
Glad I found this, as I'm having issue with mine too.
Hopefully Lightwave will sort the login issue out.

**Comment by astirling01** [comment]
If only they had released that local api we keep hearing about…..

**Comment by obot101** [comment]
Seems just logged on to HA and seems to be working fine now!

**Comment by obot101** [comment]
> Try to sign in it said it has created a configuration under my email but does not discover any devices. It has been working for the past 3 months. Here is the error:
> 
> WARNING (MainThread) [lightwave2.lightwave2] get_access_token_username: Authentication failed - if network is ok, possible wrong username/password
> 
> I have test the email and password in app multiple times any way to fix this?

**Comment by obot101** [comment]
Fixed for anyone else?

**Comment by astirling01** [comment]
No. Still broken

**Comment by spirit8000** [comment]
Still same issue here today with the integration (same error as you guys, with or without using Public API, also tried HASS restart) and also can't sign in to their web interface, so does seem to imply a LRF issue.

**Comment by astirling01** [comment]
Yeah it's definitely a lightwave issue. A quick search of Twitter and the Facebook community lightwave group shows it's affecting everyone.

**Comment by SGXander** [comment]
Glad I got homekit working for basic functions and didn't renew lightwave plus now. They are dropping the ball hard lately.

**Comment by astirling01** [comment]
Working for me now

**Comment by swampylee** [comment]
Working for me now, needs a Home Aasistant restart.

**Comment by RGarrett93** [comment]
Same, all working now after a HA reboot.
