### ISSUE TITLE
Inline relays not discovered (both Connect and Smart Series)

### ISSUE THREAD

**Issue by Valiante** [bigbadblunt/homeassistant-lightwave2#112]
I have a couple of JSJSLW821 Connect Series 500W inline relays and a LP82 (Smart Series) relay among my LightwaveRF devices.  I'm running a Link Plus (Smart Series) hub with a mixture of Connect Series and Smart Series light switches and sockets.  The official HomeKit integration only discovered the Smart Series switches, hence finding your excellent Lightwave2 component that, once installed and configured, found all my old Connect Series devices.

The only devices I'm missing are the relays, which neither the HomeKit controller or Lightwave2 seem to discover.

Please let me know what information/logs I can provide to help troubleshoot (and how to enable debug logging) as I'm extremely new to HA, having only installed the OS yesterday.

Many thanks for creating this component, and any support you can offer.

**Edit:** I found how to enable debug logging in configuration.yaml for lightwave2 only, and set the default to info (which still seems to be more detail than the original default), but I can't find anywhere what the actual default log level is. Anyway - I've attached the latest log after restarting, and I don't see the names of the relays I'm using (named Garden, Driveway and Garage in Lightwave).  Please let me know if there's anything else I can do to troubleshoot.

[home-assistant.log](https://github.com/bigbadblunt/homeassistant-lightwave2/files/11222396/home-assistant.log)

**Comment by bigbadblunt** [comment]
The original debug level is warning.

To get me useful info, you'll also need to set logging to debug on lightwave2.lightwave.

You can actually do this more easily through the configuration options for the component.

![image](https://user-images.githubusercontent.com/29158690/231839437-65e42b7d-2ea4-4051-ab87-88d99c677575.png)

Either way, if you send me a log I should be able to correct this.

**Comment by Valiante** [comment]
Brill, thanks. Extra debugging info enabled, HA restarted, new log attached.

[home-assistant.log](https://github.com/bigbadblunt/homeassistant-lightwave2/files/11230871/home-assistant.log)
