### ISSUE TITLE
Individual LED status colours

### ISSUE THREAD

**Issue by Whizzykid** [bigbadblunt/homeassistant-lightwave2#113]
Not an issue, but a curiosity. Is it possible to be able to code the LED indicators on the Smart (Gen2) switches to show different colours per switch?
At the moment you can only set the 'on' colour for all switches in the same unit. It would be cool to have different colours for different switches or even different colours depending on the scene you trigger with the switch.

**Comment by xela1** [comment]
I assume you mean in multiple gang switches? I believe the limitation is a lightwave one where if you change the colour of any switch in the unit it changes all of them. 

Depending on how lightwave drive them it could just be a software/firmware update they could deploy but it might also be a hardware limitation (I'd imagine the former though as you have different colours depending on the on/off state across the switches), but either way, it would need a change by LW first.

**Comment by Whizzykid** [comment]
Ah yes, I forgot to mention multi-gang. I was hoping somebody could do some jiggery-pokery to get this to work!

**Comment by bigbadblunt** [comment]
Agreed with @xela1 that this isn't possible as things stand. Only one LED is exposed by the LW server on a multi-gang dimmer.
