### ISSUE TITLE
Lightwave RF using Honeywell Wireless Thermostat causes integration to fail. Error:  AttributeError: 'NoneType' object has no attribute 'state'

### ISSUE THREAD

**Issue by natkins76** [bigbadblunt/homeassistant-lightwave2#118]
Hi all, don't know if anyone can help ... I've just added a Honeywell wireless thermostat T87RF to my lightwave RF system - since adding this device, the Lightwave integration in HA does not load.  From what I can see in the logs when debug logging is turned on, 

Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:137
First occurred: 09:33:44 (21 occurrences)
Last logged: 09:55:04

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/lightwave2/lightwave2.py", line 191, in _consumer_handler
    prev_value = feature.state
                 ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'state'

I've had to cut off about half of the log file as the file-size was too large for github .. but hopefully there's enough in there to track the issue?

[home-assistant_2023-09-04T08-57-01.917Z.log](https://github.com/bigbadblunt/homeassistant-lightwave2/files/12512025/home-assistant_2023-09-04T08-57-01.917Z.log)

**Comment by bigbadblunt** [comment]
I can't see the problem from your upload. Can you send me the log file directly via email, or send me a onedrive/google docs/dropbox/similar link to the full version? Also, the output from a fresh restart of HA would be preferable.

**Comment by natkins76** [comment]
Weird ... I was just running off the logs to send over as it had failed in the same way a number of times... but without any changes, it's now accepting and setting up the honeywell thermostats perfectly fine ... strange!

Thanks for taking a look anyway, I'll close the Issue
