### ISSUE TITLE
Control of the LED on Gen2 Sockets not shown in HA (whereas the LED is controllable in HA for Light Switches)

### ISSUE THREAD

**Issue by natkins76** [bigbadblunt/homeassistant-lightwave2#119]
Hi all,

I've been playing with setting the colour and brightness of the Lightwave LED's dependant on the time of day (they can be quite bright at night-time in a bedroom) ... 

In the Lightwave App, it has the ability to control the LED standby colour and the overall brightness of the LED (irrelevant of on or off) for pretty much all Gen2 devices (Sockets, light switches, heating switches, relays) ... 

However, through the HA integration, I can only see LED control for the Light Switches ... Am I being blind, or do I need to activate something somewhere to allow the LED Control for Sockets, relays, etc., to come through to HA?

any help much appreciated .. (it'll stop my wife from trying to stick insulation tape over the bedroom LED's :-) )

thanks

**Comment by bigbadblunt** [comment]
I don't have any gen2 sockets, so can't check, but the code shouldn't be discriminating between different types of device. If it's not picking up the LED, can you send me the log file from a restart of the component (with debug turned on) and I'll try and see if lightwave presents the LED differently on sockets from on light switches.

**Comment by natkins76** [comment]
Thanks for taking a look ... the following should be a link to the full log file ... https://1drv.ms/u/s!AlGMRhVqMywBic8yFKGtmR9jEH7R7w?e=L6Qeh6

Thanks

**Comment by bigbadblunt** [comment]
Thanks, I can see the log. What's the name of the socket?

**Comment by natkins76** [comment]
There should be lots in there ... Any of the gen2 plug sockets ... an example to check could be Study Socket A1 and Study Socket A2 its one physical unit with 2 plug sockets .... but any of the L42 / L42MK2 / L42MK3 devices ...  I think they're all variations of the gen2 socket that has controllable LEDs via the lightwave app.

Thanks again,

Nathan

**Comment by bigbadblunt** [comment]
I've just released a new beta, let me know if that fixes it.

**Comment by natkins76** [comment]
That's looking good to me ... im away from the house at the moment, so can't visually check, but I can see the LED controls now in home assistant for sockets, relays and heating switches and when I make changes HA, I see those changes have happened by looking at the lightwave app ... so pretty sure that's done it.

Thanks a lot

**Comment by natkins76** [comment]
Hi, just to confirm, that works perfectly now, the LED's are visible and can be properly controlled in HA for plug sockets, relays, heating switches, light switches (and even the new plug in switches)  ..  

thanks a lot for your help - I have a happy wife :-)
