### ISSUE TITLE
Not pulling in correct names of devices

### ISSUE THREAD

**Issue by ITHungry** [bigbadblunt/homeassistant-lightwave2#120]
I have 56 devices of lightwave RF all generation 2

3 Single light dimmer switches (Product code: L21) 
and 53 Smart Socket, 2 gang, (Product code: L42) ranging from L42, L42MK2, L42MK3.

when setting up the names in the lightwave up thats fine, however the latest Smart Socket, 2 gang, (Product code: L42MK3) ive just added yesterday is not pulling the correct name through Hacs on HA, just wondering if this is a limitation of the code due to how many devices I have?

Anybody else seeing this or is it just me?
I've done a thew things to check, like deleting the Hacs intergration restarting HA Yellow, reinstallaing the intergration and then 
reconnecting but the same thing I get each time. 

I know some of the previous sockets also pull in the rong name but I belive this is down to when I first lightwave, and changed the name multipil times in the lightwave app.

Just seems to be an issue more now with adding new sockets in.

I called the socket Office-Socket 6 on the lightwave app, but when it pulled the socket through the Hacs intergration it called it Switch 1254 for the Left Hand socket and called it identify_1247 for the right hand socket..

---

Home Assistant Yellow 
CM4 - Wireless: with, eMMC Flash: 32GB, RAM: 8GB 

Home Assistant 2023.10.1
Supervisor 2023.10.0
Operating System 10.5
Frontend 20231005.0 - latest

Node-RED V3.1.0
Hacs - Lightwave RF V3.5.20

**Comment by ITHungry** [comment]
> Interesting you mention this as I saw the same recently when adding new L22 switches. Not a big problem to fix, but I hope we can find a solution in the code.

Hello @Whizzykid 
How many Lightwave device do you have? out of interest.

Wonder if its a limit with Lightwave hub.

**Comment by bigbadblunt** [comment]
Can you send me a log file with debugging enabled from the startup of the component?

**Comment by bigbadblunt** [comment]
I also need debug output for `lightwave2.lightwave2` please

**Comment by ITHungry** [comment]
> I also need debug output for `lightwave2.lightwave2` please

Good Morning,
Sorry I'm not sure what your asking for? whats lightwave2.lightwave2 and how do I enable the logging for this I can only see the Lightwave v2 custom component integration which is where I anabled debug logging before. 
![Debug](https://github.com/bigbadblunt/homeassistant-lightwave2/assets/126822317/99a627ef-ab44-4c9e-a0f2-d7e6fcd9f4eb)

**Comment by bigbadblunt** [comment]
I need some extra debugging info that relates to the underlying library. This should happen automatically if you've used the method you describe above, unless you're on an older version of the component.

What version of the component are you running? If it's not the latest beta, can you update to that and resubmit the log?

**Comment by ITHungry** [comment]
Currently running Lightwave RF V3.5.20 - don't normally use Beta versions. 

How do I go about updating the current package to a Beta version?

**Comment by bigbadblunt** [comment]
Did you install through HACs? If so, go into the component, setting menu, redownload, then check "show beta versions"

![image](https://github.com/bigbadblunt/homeassistant-lightwave2/assets/29158690/4fa17654-73ff-4b62-9257-0f5e55639f7d)

**Comment by ITHungry** [comment]
Sorry for the delay, yes installed through HACs  now running in the latest beta.

[home-assistant_lightwave2_2023-11-03T19-10-01.377Z.log](https://github.com/bigbadblunt/homeassistant-lightwave2/files/13253900/home-assistant_lightwave2_2023-11-03T19-10-01.377Z.log)

**Comment by bigbadblunt** [comment]
This appears to be a fault/change with the way Lightwave is describing the objects.

Line 34 of your log file shows the information provided by Lightwave.

In case you're interested, I've reformatted and uploaded that line, line 6658 shows the problem.

[Hierarchy.txt](https://github.com/bigbadblunt/homeassistant-lightwave2/files/13258931/Hierarchy.txt)

This is possibly fixable (I would just need to get the name from somewhere else). But it would require a lot of rewriting I think. I don't know if it's a permanent change, or something one-off with your setup. If other people have the same issue, then I'll have a go at fixing.

**Comment by ITHungry** [comment]
Morning @bigbadblunt 
Thank you for looking into this, don't think its just in relation to mysetup as @Whizzykid has also seen the same issue (as he points out above), 

I have sent an email to one of my contacts from Lightwave, just to see if they can help or shed some light if anything has changed from there end. 
👍

**Comment by ikb42** [comment]
Hi, the "name" property given on the device object is effectively deprecated.
The correct (app configurable) "name"(s) is/are found in the devices featureSets which are referenced in the device featureSetGroupIds array property.  FeatureSets can be read with a group read using the ids from featureSetGroupIds.
A L42x for example would have 2 featureSets which can be named independently after the device is paired.

@bigbadblunt I'll try review the code around this in the next few days and suggest a solution.

**Comment by ikb42** [comment]
hi @bigbadblunt - it looks like the dependency on the `lightwave2` module could be the problem.
In the manifest.json:  "requirements": ["lightwave2==0.8.23"]
https://pypi.org/project/lightwave2/
This not up to date with the latest version from https://github.com/bigbadblunt/lightwave2

**Comment by nelliec** [comment]
Hiya, I just wanted to add I have the same problem here with a new setup of a Link Plus with a mix of connect and smart series devices.

Happy to help troubleshoot if I can.

**Comment by ikb42** [comment]
@bigbadblunt has very kindly allowed us to use his Lightwave repositories as the basis for ours.
We are in the process of setting these up under a fork of this repo and the underlying library repo.

@nelliec please take a look in HACS, search for Lightwave Smart, you should find our repository listed.
I'd be grateful if you would install that one and let me know what you find.

**Comment by nelliec** [comment]
Hi @ikb42 thanks for the reply and good luck with the development.

Unfortunately there's no Lightwave Smart listing on my HACS, only the homeassitant-lightwave2 one.

Do I need to wait, or enable something else?

N

**Comment by ikb42** [comment]
Hi @nelliec yes, sorry, it's not yet listed in HACS
You can add it by going to HACS, then clicking the three dots menu top right, and choose custom repositories.

Use this in the Repository field: `https://github.com/LightwaveSmartHome/homeassistant-lightwave-smart`
Category is `Integration`

Once you've done that and restarted Home Assistant, you should then find the integration in Settings -> Devices & Services -> Add Integration

**Comment by xela1** [comment]
I'll install it on my test system and give it a spin too

**Comment by xela1** [comment]
It only seems to have imported 3 devices and everything else is just under entities
![image](https://github.com/bigbadblunt/homeassistant-lightwave2/assets/357319/a1aa332b-541e-41b9-b029-a1d8bbd02648)

![image](https://github.com/bigbadblunt/homeassistant-lightwave2/assets/357319/2fa094d9-8b72-4922-9251-fe64d7765d78)

**Comment by nelliec** [comment]
hiya,

That worked for me - all my devices have appeared and now have names :)

Neal

**Comment by ikb42** [comment]
Thanks!  @xela1 we have a pull request pending on the Home Assistant brands repo to add icons

@ITHungry are you in a position to test as well?

**Comment by ITHungry** [comment]
Hello @ikb42 
My main HA Yellow Lightwave intermigration is now not functioning at all booo, however I will first test on my test system, Will install now and feedback :-)

PS thank you for jumping onboard this topic and helping out :-)

**Comment by ITHungry** [comment]
Hello @ikb42 
Unfortunately this is just not working for me at all.. Maybe i'm missing something. 

![Lightwave](https://github.com/bigbadblunt/homeassistant-lightwave2/assets/126822317/280112aa-a542-423d-9f65-e171b59e53ae)

[home-assistant_lightwave_smart_2023-11-17T02-54-15.752Z.log](https://github.com/bigbadblunt/homeassistant-lightwave2/files/13386604/home-assistant_lightwave_smart_2023-11-17T02-54-15.752Z.log)

**Comment by ikb42** [comment]
hi @ITHungry thanks for the feedback. There are quite a few, what look like, unrelated errors in that log file. Can you try disabling any other custom integrations.  Then remove and re-add the Lightwave Smart one.

**Comment by ITHungry** [comment]
Hello @ikb42 

No problem I can disable them but won’t be till I finish work tonight. 

I try a few things like deleting the integration rebooting and following all steps again to install but every time I enter the user name and password. It failed.

**Comment by xela1** [comment]
@ikb42 has anything major changed in the fork that we need to test, I saw name changes, build code and the change for featureset and something around lux, but nothing else

**Comment by ikb42** [comment]
@xela1 besides the renaming itself there aren't any major changes to test

**Comment by ITHungry** [comment]
Hello @ikb42  Ok as requested I disabled a few devices that although work fine where not plugged in and powered on this seem to stop most errors, then I rebooted HA, and then Lightwave smart integration had pulled all sockets and lights through.
I tested some sockets and lights which all seems well they turn on and off, the only thing that has not happened is pulling the devices into the areas that they should be in, I'm assuming this is due to the error I got after entering the user name and password when I first tried the integration. 

Since then I have rebooted HA and re-enabled one device that I disabled at a time then rebooting HA and checking the Lightwave Smart integration making sure it works, repeating the same until all devices that where disabled are all turned back on. all still working now. 

So not sure what caused the issue. but all seems ok now!

Maybe tomorrow I will delete the integration power down HA, and then turn back on and try installing it again just to see what happens, after all this one is my test rig.

**Comment by ITHungry** [comment]
Hello @ikb42 
Ok Still get the same issue on my HA Yellow (main system) however after disabling Robovac integration and rebooting Lightwave Smart shows up and shows all devices.

I do note that each device is not linked to the area that it should be its just blank so I have to go in and manually add each area to each device (quite a pain) when you have 56 device to do lol, but its working :-)

Also each socket is shown as a switch rather than an outlet so have to change each socket to outlet and then add mdi:power-socket-uk for the correct icon (not sure if this is something you can resolve?

Would be good when adding the integration and when its pulling in your devices you could also add each device to the area its in or better still get it to automatically do this yet again not sure if this is possible. 

Hope this helps.

**Comment by xela1** [comment]
I've now added this to my main install. Removed the old integration, restarted and added the new one. Names are pulling in correctly and all seems to be working. 

I took the opportunity to rename the devices in the app first so they pull in to HA the way I want them, instead of renaming in HA, which will hopefully cause less grief down the line.

Warning to anyone else, the events and services have changed name too, so if you're using those, make sure you edit the automatons/scripts that reference them

**Comment by ikb42** [comment]
@ITHungry thanks for that.
I'm not sure of why sockets are represented as switches and not outlets, perhaps @bigbadblunt can shed light on that.

Re adding mdi:power-socket-uk for the correct icon, depending on the switch vs socket representation, this might be something that can be improved

**Comment by bigbadblunt** [comment]
No reason, just never implemented it correctly :)

**Comment by ikb42** [comment]
Hi, I'm working on an update that will show the sockets/outlets as such and use the UK icon plus a few changes that hopefully are improvements.

Closing this issue now as solved on the new repo

**Comment by ITHungry** [comment]
@ikb42 
Thank you for you help in resolving and improving the integration 😉

**Comment by Whizzykid** [comment]
Can anybody offer me support for the new Lightwave Smart integration, please?
I can't get it to work at all, I just "failed to set up" after entering my username and password.

I've not had any answers in the official repo, sorry to post here, but I'd like to move over 

Running the latest 10.3 update

Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: 3:16:23 PM (1 occurrences)
Last logged: 3:16:23 PM

Error setting up entry <REDACTED EMAIL ADDRESS> for lightwave_smart
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lightwave_smart/__init__.py", line 89, in async_setup_entry
    await link.async_get_hierarchy()
  File "/usr/local/lib/python3.12/site-packages/lightwave_smart/lightwave_smart.py", line 623, in async_get_hierarchy
    await self._async_read_groups()
  File "/usr/local/lib/python3.12/site-packages/lightwave_smart/lightwave_smart.py", line 654, in _async_read_groups
    self.get_featuresets(featuresets, devices, features)
  File "/usr/local/lib/python3.12/site-packages/lightwave_smart/lightwave_smart.py", line 863, in get_featuresets
    new_featureset.product_code = device["productCode"]
                                  ~~~~~~^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by bigbadblunt** [comment]
Are you sure your password is entered correctly? 

You can try it on https://manager.lightwaverf.com/ to make sure.

**Comment by ikb42** [comment]
For clarity https://manager.lightwaverf.com/ is useful if you were originally a Connect series user.  If started with Smart series you can use https://my.lightwaverf.com/a/login
If you were an Connect series user and are now a Smart series user and no longer use the Connect series hub/wifi link, then it is a good idea to ask Lightwave support to de-link your Connect account.
