### ISSUE TITLE
HASS 2024.1.x - Deprecated Constants

### ISSUE THREAD

**Issue by uvjim** [bigbadblunt/homeassistant-lightwave2#122]
The HASS log is showing the following since upgrading to 2024.1.1.
I believe it is in line with this https://developers.home-assistant.io/blog/2023/12/19/constant-deprecation/

```
Logger: homeassistant.const
Source: helpers/deprecation.py:204
First occurred: 4 January 2024 at 21:34:27 (14 occurrences)
Last logged: 4 January 2024 at 21:34:27

ELECTRIC_POTENTIAL_VOLT was used from lightwave2, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfElectricPotential.VOLT instead, please report it to the author of the 'lightwave2' custom integration
ELECTRIC_CURRENT_MILLIAMPERE was used from lightwave2, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfElectricCurrent.MILLIAMPERE instead, please report it to the author of the 'lightwave2' custom integration
DEVICE_CLASS_CURRENT was used from lightwave2, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.CURRENT instead, please report it to the author of the 'lightwave2' custom integration
DEVICE_CLASS_VOLTAGE was used from lightwave2, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.VOLTAGE instead, please report it to the author of the 'lightwave2' custom integration
DEVICE_CLASS_ILLUMINANCE was used from lightwave2, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.ILLUMINANCE instead, please report it to the author of the 'lightwave2' custom integration
```
```
Logger: homeassistant.components.sensor
Source: helpers/deprecation.py:204
Integration: Sensor (documentation, issues)
First occurred: 4 January 2024 at 21:34:27 (4 occurrences)
Last logged: 4 January 2024 at 21:34:27

STATE_CLASS_MEASUREMENT was used from lightwave2, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorStateClass.MEASUREMENT instead, please report it to the author of the 'lightwave2' custom integration
STATE_CLASS_TOTAL_INCREASING was used from lightwave2, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorStateClass.TOTAL_INCREASING instead, please report it to the author of the 'lightwave2' custom integration
```
```
Logger: homeassistant.components.binary_sensor
Source: helpers/deprecation.py:204
Integration: Binary Sensor (documentation, issues)
First occurred: 4 January 2024 at 21:34:27 (6 occurrences)
Last logged: 4 January 2024 at 21:34:27

DEVICE_CLASS_WINDOW was used from lightwave2, this is a deprecated constant which will be removed in HA Core 2025.1. Use BinarySensorDeviceClass.WINDOW instead, please report it to the author of the 'lightwave2' custom integration
DEVICE_CLASS_PLUG was used from lightwave2, this is a deprecated constant which will be removed in HA Core 2025.1. Use BinarySensorDeviceClass.PLUG instead, please report it to the author of the 'lightwave2' custom integration
DEVICE_CLASS_MOTION was used from lightwave2, this is a deprecated constant which will be removed in HA Core 2025.1. Use BinarySensorDeviceClass.MOTION instead, please report it to the author of the 'lightwave2' custom integration
```
```
Logger: homeassistant.components.cover
Source: helpers/deprecation.py:204
Integration: Cover (documentation, issues)
First occurred: 4 January 2024 at 21:34:27 (6 occurrences)
Last logged: 4 January 2024 at 21:34:27

SUPPORT_CLOSE was used from lightwave2, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.CLOSE instead, please report it to the author of the 'lightwave2' custom integration
SUPPORT_OPEN was used from lightwave2, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.OPEN instead, please report it to the author of the 'lightwave2' custom integration
SUPPORT_STOP was used from lightwave2, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.STOP instead, please report it to the author of the 'lightwave2' custom integration
```
```
Logger: homeassistant.components.climate.const
Source: helpers/deprecation.py:204
Integration: Climate (documentation, issues)
First occurred: 4 January 2024 at 21:34:26 (8 occurrences)
Last logged: 4 January 2024 at 21:34:27

SUPPORT_TARGET_TEMPERATURE was used from lightwave2, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please report it to the author of the 'lightwave2' custom integration
SUPPORT_PRESET_MODE was used from lightwave2, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.PRESET_MODE instead, please report it to the author of the 'lightwave2' custom integration
CURRENT_HVAC_HEAT was used from lightwave2, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACAction.HEATING instead, please report it to the author of the 'lightwave2' custom integration
CURRENT_HVAC_IDLE was used from lightwave2, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACAction.IDLE instead, please report it to the author of the 'lightwave2' custom integration
CURRENT_HVAC_OFF was used from lightwave2, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACAction.OFF instead, please report it to the author of the 'lightwave2' custom integration
```

**Comment by ianphillpott** [comment]
I'm getting "This entity is no longer being provided by the lightwave2 integration. If the entity is no longer in use, delete it in settings." for all the current, voltage and consumption entities for all lights and sockets as well.

**Comment by ins4neuk** [comment]
I just rolled back to the last 2023 update and they came back and working again so defo something to do with the 2024 update.

**Comment by ikb42** [comment]
Hi, just to let you know the constant deprecation warnings also need to be addressed in the updated branch of this integration https://github.com/LightwaveSmartHome/homeassistant-lightwave-smart

**Comment by bigbadblunt** [comment]
I've merged the PR and released a new version. 

However, you should move across to https://github.com/LightwaveSmartHome/homeassistant-lightwave-smart when you can - I'm only doing minimal maintenance of this version, and the newer version is already a few commits ahead.

**Comment by ins4neuk** [comment]
> I've merged the PR and released a new version.
> 
> However, you should move across to https://github.com/LightwaveSmartHome/homeassistant-lightwave-smart when you can - I'm only doing minimal maintenance of this version, and the newer version is already a few commits ahead.

cheers for the quick sort out. quick question thou you say move over to the newer version above I'm still using this one  but i have a lot of switched all renamed and a lot of button press automations set up. how can i migrate or will i need to set everything back up again??

**Comment by ins4neuk** [comment]
😭😭😭😭😭😭😭😭😭😭😭😭

I've got every switch in the house doing something lol like 4 presses for hoovering that room. 3 for curtains etc etc 😂😂👍

**Comment by xela1** [comment]
> 😭😭😭😭😭😭😭😭😭😭😭😭
> 
> I've got every switch in the house doing something lol like 4 presses for hoovering that room. 3 for curtains etc etc 😂😂👍

yeah, it took a while, some I changed in the yaml files, some I use watchdog for, and some things I just completely re-wrote but I used it as a good opportunity for a spring clean to get things named uniformly for once

**Comment by ins4neuk** [comment]
Yeah I'll have a think. Which is a better way of doing it.  Think that's a job for next week now

**Comment by araines** [comment]
> However, you should move across to https://github.com/LightwaveSmartHome/homeassistant-lightwave-smart when you can - I'm only doing minimal maintenance of this version, and the newer version is already a few commits ahead.

Is the plan for this new repo to become the "main" project then?  It would be nice to get a note on the README or something (or maybe there is and I missed it!) to point people over.  Also I'm curious if there is any info as to why the move, rather that just releasing it as a new version here?

**Comment by ins4neuk** [comment]
right i'm well confused. ive put 2024.1.4 version on and its still saying that the sensors are not working... how ever according to my hacs integration i'm on this

![image](https://github.com/bigbadblunt/homeassistant-lightwave2/assets/28991053/50429d0c-0645-489d-9c19-c929e8a93e1d)

but you also said about swapping over to the new version so if i'm right i need to be on 

https://github.com/LightwaveSmartHome/homeassistant-lightwave-smart

how ever my Hacs repo is showing as that

![image](https://github.com/bigbadblunt/homeassistant-lightwave2/assets/28991053/45909d5a-3244-4e63-a51f-ba3788eae64f)

but then when i check the lastest version on that new link, https://github.com/LightwaveSmartHome/homeassistant-lightwave-smart, 

![image](https://github.com/bigbadblunt/homeassistant-lightwave2/assets/28991053/72194db2-e957-43ef-89a3-ebba01dcb166)

which hasn't been updated.

what the hell am i doing wrong!!!

**Comment by bigbadblunt** [comment]
The fix hasn't been applied to the other repo. See https://github.com/LightwaveSmartHome/homeassistant-lightwave-smart/issues/4

**Comment by ins4neuk** [comment]
Morning.

Yeah that's what confusing me. Mine is showing as using the version that's had the fix the beta one.  But my report is showing the name for the one that hasn't and its not letting me change anything 🤣🤣

**Comment by ins4neuk** [comment]
right i'm still getting no where lol.

i'm going to remove everything and start again.

which link should i add and what version to get everything working.

**Comment by incarvr6** [comment]
> I've merged the PR and released a new version.
> 
> However, you should move across to https://github.com/LightwaveSmartHome/homeassistant-lightwave-smart when you can - I'm only doing minimal maintenance of this version, and the newer version is already a few commits ahead.

So does it means this integration is not supported maintained anymore? I didn't know that there is different version now..

**Comment by ikb42** [comment]
An update to this, thanks to @xela1 the constant deprecation warnings are now also fixed in https://github.com/LightwaveSmartHome/homeassistant-lightwave-smart 
The new repo is not yet included with HACS, there is a pull request on HACS default repo pending review and merge though which will hopefully see it included in the next month or so.
I'll look to update the readme here to point to the new repo.

**Comment by ikb42** [comment]
I think we can close this issue now.
Please migrate to the new repo when you can https://github.com/LightwaveSmartHome/homeassistant-lightwave-smart
