### ISSUE TITLE
Add support for Thermostatic Radiator Valves (TRV)

### ISSUE THREAD

**Issue by bigbadblunt** [bigbadblunt/homeassistant-lightwave2#14]
Follow on from issue identified during closure of issue #13, need to add support for TRVs

**Comment by bigbadblunt** [comment]
OK, I can see the valve level commands. Should be doable.

I can't obviously work out what's going on with the playroom light. Is it definitely a device? The commands in the log file that relate to "Playroom lights" appear to be actions on a group, where the underlying device is actually called "Master Bedroom"? Any ideas?

**Comment by ianphillpott** [comment]
So, seems when I moved house something somewhere still thinks the light switch is master bedroom! Screwey. Gonna try changing the details and restarting to see if it clears! Also got to correct the know issue of double Smart sockets insisting both side is the same name but hopefully renaming will solve that.

Good luck with the TRVs. And glad you could understand all that log! Gotta get my head back in the computing game. Lots changed since my degree in 2003!!

**Comment by ianphillpott** [comment]
Also, do I need to leave debug on as long file expanding rapidly :-)

**Comment by bigbadblunt** [comment]
I've uploaded a new release: v2.3.2beta. You should be able to install this through HACs (you will need to enable beta releases; in HACS, go into the list of installed integrations and choose "reinstall", it should be obvious from there).

If the new component works, there should be an option within the entities to choose a preset radiator level. If it doesn't work, send me the log, if it does work can you try different actions and see whether there are bits that aren't functioning?

![image](https://user-images.githubusercontent.com/29158690/83800052-b3cfb900-a69e-11ea-9a24-6df7a90d9a1e.png)

**Comment by ianphillpott** [comment]
Installed (after working out how to get beta on) but no options for positions coming up that i can see...
[home-assistant - Copy.log](https://github.com/bigbadblunt/homeassistant-lightwave2/files/4737126/home-assistant.-.Copy.log)

**Comment by bigbadblunt** [comment]
Thanks, found the first bug. Have pushed a new version for you to try.

Just for clarification, if it's working it should look something like this:

![image](https://user-images.githubusercontent.com/29158690/83898548-f9e45580-a74e-11ea-85de-c4b74f34c4f0.png)

**Comment by ianphillpott** [comment]
Right that has appeared. A couple of issues in that when you select any option it then jumps to 100%. I cant do much testing as kid gone to bed and I don't want radiators going nuts so will do a reboot and log some stuff in the morning (log gonna be huge otherwise!)

**Comment by bigbadblunt** [comment]
Could you add another couple of lines to collect some more logging data please?

```
logger:
  default: warning
  logs:
    custom_components.lightwave2: debug
    custom_components.lightwave2.climate: debug
    lightwave2.lightwave2: debug
```

**Comment by ianphillpott** [comment]
Right, added lines, reset server, first changed the settings of the Livingroom Radiator Small within HA then used the lightwave app to change the same radiator.

Hopefully this gives you something to work with!
[home-assistant - Copy.log](https://github.com/bigbadblunt/homeassistant-lightwave2/files/4739708/home-assistant.-.Copy.log)

**Comment by bigbadblunt** [comment]
I've pushed a new version (v2.3.2beta3). Let me know what happens.

**Comment by ianphillpott** [comment]
Ok so installed and tested on 1 TRVs. Seems to work. When set to 20% it reports 20% in the lightwave app, when set to 40% in lightwave it recognises that in HA.

Will try and run further tests over the next week but fingers crossed it is sorted!!

You sir are a legend!

**Comment by bigbadblunt** [comment]
Cool!

A couple of things I wasn't not 100% sure about:

1) Changing between "target temperature" and "manual" settings. If you could try moving from one to the other (both in HA and Lightwave) and seeing if behaviour is as expected.
2) How to represent this in HA. I'm not sure how it looks in the official Lightwave app/web app? Are there just 5 settings in the app, and how are they described? I'd like the HA behaviour/description to be similar to that in the Lightwave apps (as far as is possible given HA constrains things to a certain template).

**Comment by ianphillpott** [comment]
Good afternoon. Sorry it has been a while - working in Healthcare you can imagine things have been nuts!

So I have attached recent logs as well as some pictures of how things are displayed.

There are 3 sets of settings - State which is On or Off, Position which is 0 to 5, and Target (temperature) which is from 0 to 40 degrees in 0.5 degree steps.

When you set a position it sets the TRV to 40 degrees and fixes the % open - which thanks to you is now possible from HA!
If you turn it off, it sets the TRV to 0% but does not change the temperature

If you set a temperature it will then turn on if needed, then turn off if needed, the set target will remain the same. If you set state to off it overrides the urge of the TRV to turn on and shuts it off but again leaves the target as it was.

I think that makes sense :-/

Thanks again for this. 




[home-assistant.log](https://github.com/bigbadblunt/homeassistant-lightwave2/files/4960512/home-assistant.log)
![Screenshot_20200722-145043_Lightwave](https://user-images.githubusercontent.com/66304965/88187323-47991c80-cc2e-11ea-9444-27ba7911cf5b.jpg)
![Screenshot_20200722-145048_Lightwave](https://user-images.githubusercontent.com/66304965/88187325-4831b300-cc2e-11ea-98e4-066c2945133a.jpg)
![Screenshot_20200722-145053_Lightwave](https://user-images.githubusercontent.com/66304965/88187328-48ca4980-cc2e-11ea-9b31-c1e73c0ddff9.jpg)
![Screenshot_20200722-150225_Lightwave](https://user-images.githubusercontent.com/66304965/88187332-48ca4980-cc2e-11ea-9202-d9a3681040dc.jpg)

**Comment by bigbadblunt** [comment]
Hi Ian, I think that's the same behaviour I've tried to implement in ha. Have you spotted anything different?

**Comment by ianphillpott** [comment]
So one thing I have noticed:

When you select Auto it changes back to target temperature mode. On the app there is a 0 which sets the valve to 0 and sets the state to off. Can't do this in HA as only has an auto option so if the target temp is above the room temp there is no way to shut off the valve using the preset but you have to set operation to Off.

So it will still function but you need to do things a slightly different way. Perhaps may be useful to have 100% 80% 60% 40% 20% 0% and Auto in the operation list, 0% setting trv to 0 and state to off if that is possible?

**Comment by bigbadblunt** [comment]
Closing as support has been added and is working. For any changes to how this works, please raise a new issue/feature request.
