### ISSUE TITLE
Exception on startup 

### ISSUE THREAD

**Issue by robcos** [bigbadblunt/homeassistant-lightwave2#15]
Since a week or so I'm getting errors when starting homeassistant.
I'm not sure if there has been any changes to the code of this integration or the api has started to return something different, however it seems that     **features["dimLevel"][1]** is None which cause the call to fail.

```
2020-06-20 14:38:22 ERROR (MainThread) [homeassistant.components.light] Error while setting up lightwave2 platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/lightwave2/light.py", line 20, in async_setup_entry
    lights.append(LWRF2Light(name, featureset_id, link, url))
  File "/config/custom_components/lightwave2/light.py", line 39, in __init__
    "dimLevel"][1] / 100 * 255))
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
```

**Comment by robcos** [comment]
FYI I also get the following message, just before the exception, I don't know if it is relevant:
` [lightwave2.lightwave2] Received API response 404 {"message":"Structure not found"} {'message': 'Structure not found'}`

**Comment by robcos** [comment]
v2.2.0 is fine.
v2.3.2beta3 still has the issue.

**Comment by bigbadblunt** [comment]
What version of HA are you using? Versions of this component later than 2.2.0 require HA 110 or later.

If you're using a newer version of HA, can you please post full logs?

**Comment by robcos** [comment]
I am on version 0.111.4

**Comment by bigbadblunt** [comment]
The log file posted doesn't have any errors in. Can you post one with the error reproduced?

**Comment by robcos** [comment]
[home-assistant.log](https://github.com/bigbadblunt/homeassistant-lightwave2/files/4808451/home-assistant.log)
Gosh...of course. Here it is, when running v2.3.1 and HA 0.111.4

**Comment by bigbadblunt** [comment]
Just pushed a new version, let me know if it works.

**Comment by bigbadblunt** [comment]
PS v2.3.2beta4

**Comment by robcos** [comment]
Thanks! It works great.
