### ISSUE TITLE
Please support multiple hubs

### ISSUE THREAD

**Issue by robcos** [bigbadblunt/homeassistant-lightwave2#18]
Please add support for multiple hubs. It will provide a piece of functionality that unfortunately cannot be achieved with the official support from LightwaveRF.

Thread https://community.home-assistant.io/t/multiple-lightwaverf-integrations-multiple-hubs/223064?u=roberto_cosenza

**Comment by robcos** [comment]
By the way, I'm very happy to help if pointed the right direction. I'm a software developer

**Comment by bigbadblunt** [comment]
I don't think this is a problem I can solve elegantly. My component/lightwave library has two control schemes:

1) pretending to be the official app and communicating with the LW servers that way
2) using the official lightwave API, which also routes via the LW servers

Neither of these has support for two hubs. All I do is send a message to the LW servers which then deals with the hub. I have no way of extending it to a second hub.

You could set up two hubs with different usernames? But each device could only be paired with one hub. If this is the solution you have in mind I think this should already be achievable by adding another instance of the custom component with a different domain.

a) copy all files from
~/.homeassistant/custom_components/lightwave2
to (say)
~/.homeassistant/custom_components/lightwave2A

b) change the domain references from "lightwave2" to "lightwave2A" in:

line 2 of custom_components/lightwave2/manifest.json
line 1 of custom_components/lightwave2/const.py

My immediate thought is that adding this as functionality into the main component would require a substantial rewrite.

**Comment by robcos** [comment]
Two usernames is what I have in mind. Users of HomeAssistant won’t know/care which username is used to toggle a switch. If it is not trivial to support two usernames in the integration I will go the “separate integration” but it would have been nice to be able to upgrade both integrations automatically

**Comment by robcos** [comment]
Quick update on this. I never noticed this earlier but the lightwave app does allow you to have multiple "locations", each with is own hub. It's like having multiple accounts under a single user name. You can select one location in the account settings and from that moment on the app only shows switches linked to that hub.
Interestingly, I can't find a way to switch between multiple locations on the my.lightwaverf.com website so it's either a poorly done feature or recently added.

**Comment by bigbadblunt** [comment]
Interesting! I'm pretty sure this is new - I briefly looked into having two hubs but it wasn't supported and I found a spot in my house that just about reaches everywhere.

Do you have this set up? It might be straightforward to add support, depending on how it works. If you have the appetite to try, can you increase the level of logging in home assistant, use the app to communicate with devices in the different hubs and send me the output?

**Comment by robcos** [comment]
Yes I have it set up. I added just one switch for the time being and it
does not show in home assistant. I'll send you the full logs once I have a
minute.
What packages do you want the logs for?

**Comment by robcos** [comment]
Great news...it actually just works out of the box. The devices on the new hub were disabled but they were actually there!

**Comment by bigbadblunt** [comment]
Ha! Easier to fix than I first thought ;)
