### ISSUE TITLE
New exception at startup

### ISSUE THREAD

**Issue by robcos** [bigbadblunt/homeassistant-lightwave2#19]
Similarly to #15, I'm getting a new exception at startup

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 179, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/config/custom_components/lightwave2/light.py", line 20, in async_setup_entry
    lights.append(LWRF2Light(name, featureset_id, link, url))
  File "/config/custom_components/lightwave2/light.py", line 38, in __init__
    self._lwlink.get_featureset_by_id(self._featureset_id).features[
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
```
Home Assistant 0.113.3
LW v2.3.2beta4
[home-assistant.log](https://github.com/bigbadblunt/homeassistant-lightwave2/files/5241380/home-assistant.log)

**Comment by bigbadblunt** [comment]
@robcos I'm pretty sure this is related to multiple hubs. The call to the lightwave API is failing when it tries to read features that are on your second hub. This looks like a change in behaviour of the API that I can't code around.

Can you try the emulated version of the API (go into configuration->integrations->lightwave options, uncheck "Use public API" and restart)?

**Comment by robcos** [comment]
Same error with the non public API. They must have changed something because nothing changed in my system.
In general, could we make this kind of errors non fatal? What I mean can the failing feature be skipped rather than letting the whole integration fail? A

**Comment by bigbadblunt** [comment]
I will look at making this non fatal, but it'll be a bit of work to make it fail gracefully. At the moment the library does a batch read of the states of all entities. The two problems are:
1) if the read fails for any single entity, the server sends back an invalid response for all entities in the request
2) if I change to reading the entities one by one instead of as a batch, the server will stop responding after a certain number of requests as it is rate limited
Let me have a think and see how to make it fail as gracefully as possible

**Comment by bigbadblunt** [comment]
Can you send me the log files for the non-public setup? If this works through the app, in principle I should be able to get it to work via the non-public method (as that's using the exact same communication as the app uses). I can't promise, as that relies on me guessing how the app does it, but there might be something in the log that's useful.

**Comment by robcos** [comment]
I had not noticed but now the exception is different
2020-09-21 17:30:51 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Lightwave 2 for lightwave2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 219, in async_setup
    result = await component.async_setup_entry(  # type: ignore
  File "/config/custom_components/lightwave2/__init__.py", line 102, in async_setup_entry
    await link.async_get_hierarchy()
  File "/usr/local/lib/python3.8/site-packages/lightwave2/lightwave2.py", line 210, in async_get_hierarchy
    await self.async_update_featureset_states()
  File "/usr/local/lib/python3.8/site-packages/lightwave2/lightwave2.py", line 247, in async_update_featureset_states
    x.features[y][1] = value["items"][0]["payload"]["value"]
KeyError: 'payload'


[home-assistant.log](https://github.com/bigbadblunt/homeassistant-lightwave2/files/5256763/home-assistant.log)

**Comment by bigbadblunt** [comment]
Hmmm. Seems to be the same problem. I've emailled lightwave support to see if I get any joy that way.

**Comment by bigbadblunt** [comment]
@robcos lightwave say some new server code was deployed yesterday. Can you try again and see if it works? Trying both versions of the API please?

If it still doesn't work are you ok for me to share some of your details with lightwave (specially your username and the unique identifiers of the devices that don't work)

**Comment by robcos** [comment]
No changes
2020-09-23 10:35:12 ERROR (MainThread) [homeassistant.components.light] Error while setting up lightwave2 platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 179, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/config/custom_components/lightwave2/light.py", line 20, in async_setup_entry
    lights.append(LWRF2Light(name, featureset_id, link, url))
  File "/config/custom_components/lightwave2/light.py", line 38, in __init__
    self._lwlink.get_featureset_by_id(self._featureset_id).features[
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

Please do share my info. Thanks

**Comment by bigbadblunt** [comment]
OK, I'm waiting for Lightwave to get back to me. In the meantime, I've pushed a new version of the integration that should allow you to set up multiple instances of the components with different usernames. You will need to delete any previous versions and set them up again. If you wanted to try setting up your second hub with a different user name, that would give a workaround.

Note that this only works properly with the private API - with the public API Home Assistant won't receive any state changes the happen from another source (i.e. the status in HA may get out of sync with the real world). It looks like Lightwave broke something in the public API so I can't receive notifications from the server when state changes.

**Comment by bigbadblunt** [comment]
New version is v3.0.0beta

**Comment by robcos** [comment]
That's awesome. I had noticed recently that some updates were not reflected
in HA but could never pinpoint when that started to happen so big thanks
for looking into both  issues

**Comment by bigbadblunt** [comment]
@robcos can you check that you're able to operate devices on the second hub from the app please? Lightwave support say your second hub is showing as offline.

**Comment by robcos** [comment]
Indeed, my kids had turned it off! It's now up and running..

**Comment by bigbadblunt** [comment]
Is the component working?

**Comment by robcos** [comment]
Yes! Seems to work fine with both Hubs
