### ISSUE TITLE
Invalid Config

### ISSUE THREAD

**Issue by mjcilia** [bigbadblunt/homeassistant-lightwave2#20]
Hey, 

Firstly thank you for setting up this integration, unfortunately I get an invalid config notification after I link my account via the integrations panel. Screenshot and log as per below:

![Capture](https://user-images.githubusercontent.com/4655507/93905333-240c5400-fcfb-11ea-8481-0955afb78b79.PNG)

![Log](https://user-images.githubusercontent.com/4655507/93905490-50c06b80-fcfb-11ea-8eec-8f3887fc38d9.PNG)

**Comment by bigbadblunt** [comment]
What version of HA are you using? This looks like it might be the result of using an older version.

**Comment by bigbadblunt** [comment]
More specifically, the component requires at least version 110 of HA

**Comment by mjcilia** [comment]
I am using v0.106.4... That explains it then. Thanks for your prompt reply.

**Comment by bigbadblunt** [comment]
No worries. Are you able to upgrade? I can backport it if you don't want to upgrade, but it might take a week or so to get around to it

**Comment by mjcilia** [comment]
Hey. I upgraded HA and works like a charm. Much obliged sir.

**Comment by bigbadblunt** [comment]
I added in code to allow the integration to work with older versions of HA. This in in the latest release (v3.0.0beta)
