### ISSUE TITLE
Setting thermostat temperatures within automations / scripts etc

### ISSUE THREAD

**Issue by ianphillpott** [bigbadblunt/homeassistant-lightwave2#21]
Hi,

Now we are into the colder months i'm discovering a couple of issues with my TRVs and thermostat.

For some reason I am unable to set the temperature of the thermostat within automations etc. And it keeps resetting to 13 degrees when one of my radiators come on meaning whilst it is on, it will only provide heat if the temp is below 13. (was trying to write a routine to mitigate this as if I can tell it what temp to set the thermostat at the same time it wouldn't be an issue!)

I can see temperature and lwrf_targetTemperature within the entity but am unable to set them within routines, only read them. Within the entity in Lovelace I can modify the temperature and that works perfectly but without the automation/script options I can't get all the home automation etc it to work properly and I still have to do everything manually.

Any thoughts?

The presets you did are working brilliantly.

Cheers

Ian

P.S If you need logs of particular actions let me know and ill start logging and run through a whole load of actions for you.

**Comment by bigbadblunt** [comment]
@ianphillpott how are you trying to set the temperature in your routine? You won't be able set the attribute directly, you'll need to call the climate.set_temperature service with the name of the entity and the temperature you want to set.

![image](https://user-images.githubusercontent.com/29158690/96755536-bff8b080-13ca-11eb-8ba7-6df43b1edb40.png)

**Comment by ianphillpott** [comment]
Ahh so it can be done, I was just being a monumental numpty 🤣

Excellent. This is very useful! Consider the issue, which clearly is myself, closed! ☺️
