### ISSUE TITLE
Lightwave V1 Mood switches

### ISSUE THREAD

**Issue by MikeLDPT** [bigbadblunt/homeassistant-lightwave2#25]
Hi @bigbadblunt  

I don't know if you (or anyone) has considered the V1 Mood switches? These are not wired, and are not visible via the integration.  They are used to "remote control" the switches, and I guess may not be entities in the lightwave hub as such.  My research identifies that they are going to be RF 433Mhz devices (as are all V1 products).   Lightwave have not yet achieved the equivalent as a V2 product and I had a thought that the V1 Mood Switch may be re-usable via HA to connect to and control either or both V1 or V2 Lightwave products(?)

If you have mood switches I wonder if you have considered something along the same lines?  I saw some posts on accessing these via RF 433MHz but not really a detailed solution to achieving it.

I didn't expect it to be so hard to identify a suitable and compatible "off the shelf" RF 433Mhz piece of hardware with decent range (my first stumbling block) for a Raspberry Pi!

It would be interesting to know if you have tried this, and if you may know of a post somehwere that gives a detailed walk through.

Thanks

**Comment by bigbadblunt** [comment]
I don't have a mood switch, but I do have a LW100 remote, which I think works the same.

These don't go via the hub at all - they are directly linked to the device they're controlling (I assume this is why they don't work with V2 switches as they use a different protocol).

So I can't detect activity from the remotes as the hub is blind to them. You could try capturing the signals from the remote using a generic 433MHz receiver. Rfxcom seems to support the lightwave protocol (https://www.home-assistant.io/integrations/rfxtrx/)
 but I've not tried it myself.

**Comment by MikeLDPT** [comment]
Thanks @bigbadblunt.  I believe your LW100 will be similar to LW101 which I have and RF 433Mhz.  I have 3 units and think it would be useful to be able to use them within HA to control pretty much anything when one of their buttons is pushed.  Firstly and specifically to initiate a V2 Lightwave switch. I believe I have quite a few other RF devices about as well: Oregon weather station components for example.  

I had found the RFXCOM RFXTRX integration, but have difficulty finding any hardware to use with it.  All RFXCOM kit seems to be "out of stock".  Raspberry Pi specific 433Mhz receiver/transmitter have some reports of only being a few meters in range. RFLINK alternative also no hardware.  There are some Chinese RF 433Mhz USBs which take many weeks to arrive, but they don't have startling reviews either. Just starting to look at Sonoff RF bridge and possibility of flashing with Tasmota.  This may be "one for the back burner" as they say.
