### ISSUE TITLE
OOOps ... seem to have forked your project by mistake

### ISSUE THREAD

**Issue by MikeLDPT** [bigbadblunt/homeassistant-lightwave2#29]
Hi Bigbadblunt,

Back in September I seem to have forked your project by mistake.  I am new to all this still!  Is there a way to remove that fork do you happen to know?  I think leaving it would be confusing for others.

Regards.

**Comment by bigbadblunt** [comment]
Go to settings

![image](https://user-images.githubusercontent.com/29158690/107143193-9e94e380-692b-11eb-97ad-adb570ef5d9f.png)

then right at the bottom "delete this repository"

**Comment by MikeLDPT** [comment]
Thanks! its now deleted.
