### ISSUE TITLE
Warning got since update to HA Core 2021.3.2

### ISSUE THREAD

**Issue by lolongan** [bigbadblunt/homeassistant-lightwave2#30]
Got the warning below in logs after updating to latest version HA Core 2021.3.2.

`2021-03-07 15:46:09 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'lightwave2'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'lightwave2`

**Comment by bigbadblunt** [comment]
Should be fixed in latest release
