### ISSUE TITLE
[INFO] Local Control API

### ISSUE THREAD

**Issue by delid4ve** [bigbadblunt/homeassistant-lightwave2#32]
Hi @bigbadblunt 

I have written/maintain an openhab integration for lightwave and thought this may be of interest:

I again contacted lightwave regarding a local api, this time to be told that it is in development stage, but new product lineups for 2021 are taking priority at present.

so watch this space.. finally.. we may actually get this 👍

**Comment by bigbadblunt** [comment]
Fingers crossed!

**Comment by gary-sargent** [comment]
@bigbadblunt is this the local API? https://api.lightwaverf.com/

**Comment by bigbadblunt** [comment]
That's the API for series one devices.
