### ISSUE TITLE
New energy consumption wrong unit of measure?

### ISSUE THREAD

**Issue by totalitarian** [bigbadblunt/homeassistant-lightwave2#39]
Hi, thanks for adding the new energy sensors.

I have one light that is showing as 7,893 kWh in HA

![image](https://user-images.githubusercontent.com/2385696/132956820-c2e4b1a9-f8ce-46b5-9ea0-0bcf1c97ceef.png)

but only 7.9 kWh in the app

![image](https://user-images.githubusercontent.com/2385696/132956856-b6a30c74-ad3e-49b9-a8b6-098389dd6c1f.png)

I suspect the app is the correct value. Guess the integration is multiplying by 1000 somewhere?

**Comment by totalitarian** [comment]
![image](https://user-images.githubusercontent.com/2385696/132956961-ee184dec-c7e5-44a4-9b9c-5fa59167fbc7.png)

**Comment by bigbadblunt** [comment]
Ha. Maybe you just have some very inefficient lights :)

This is an easy fix, I've just specified the wrong units... thanks for the report, will fix asap

**Comment by bigbadblunt** [comment]
Hopefully fixed. Thanks for testing the beta and providing feedback.

**Comment by totalitarian** [comment]
My pleasure and thanks for the quick fix! Any way to delete the erroneous values from the energy dashboard at all?

**Comment by bigbadblunt** [comment]
I'm not sure about deleting the values from the dashboard (I've not used it).
