### ISSUE TITLE
Feature request: Detect button presses on dimmer devices

### ISSUE THREAD

**Issue by bensmithuk** [bigbadblunt/homeassistant-lightwave2#40]
With the new version 5 firmware for dimmers, automations can be triggered directly with button presses - both on and off button can trigger different things. Is it possible to observe those via the API and for the integration to make them available to Home Assistant?

**Comment by bigbadblunt** [comment]
I can have a look, but I've not had much luck in the past figuring out the automations.

Can you point me at how this works? I've updated my firmware and the app, but can't see how to do what you suggest.

**Comment by bensmithuk** [comment]
To find it in the Lightwave app open a dimmer device (to the screen where you can set dimmer level / switch), then hit Settings and Multi-press (under the Advanced) heading. This lets you attach custom automations to the up / down buttons.

Confusingly, although it's called 'multi-press' automations can be triggered from 1 press. I think you need their new PLUS subscription to use it: https://lightwaverf.com/2021/09/03/lightwave-plus/

My interest is using this function to trigger stuff in Home Assistant (if Lightwave reports these button presses via its API). I already do this by grouping Lightwave dimmer circuits with Hue lamps, but this new feature might allow more complex stuff (?)

I don't really use Lightwave automations at all.

**Comment by bigbadblunt** [comment]
OK, I've pushed a new release that does this, albeit not very elegantly. There is now an event `lightwave2.click` that you can listen for. See below for an example of this event firing

![image](https://user-images.githubusercontent.com/29158690/133152749-2fedcbc9-3457-4c56-8b21-761c6878df89.png)

The "code" returned is the type of click:

Code|Hex|Meaning
----|----|----
257|101|Up button single press
258|102|Up button double press
259|103|Up button triple press
260|104|Up button quad press
512|200|Up button press and hold
768|300|Up button release after long press
4353|1101|Down button single press
4354|1102|Down button double press
4355|1103|Down button triple press
4356|1104|Down button quad press
4608|1200|Down button press and hold
4864|1300|Down button release after long press

Let me know if it works. At some point I'll add something to return the type of button press in the event report.

**Comment by bigbadblunt** [comment]
PS, this only works for light switches. I don't have any sockets to test on (I'm not even sure if the new firmware applies to those?). If you have sockets and are willing to do a bit of testing, I can extend the above code to those?

**Comment by paularnol** [comment]
I have sockets and I’m willing to test for you.

**Comment by bigbadblunt** [comment]
OK, just released a new version (v3.4.0beta2) with some test code for sockets. If you could go into developer tools->events, and listen for "lightwave2.click" events.

1) do you get any events? and (2) what are the codes that correspond to whatever you push on the physical socket?

**Comment by bensmithuk** [comment]
This is amazing. Thank you. I need to switch from a HACS to a manual install and I'll test ASAP.

**Comment by bigbadblunt** [comment]
You can install beta versions through HACs. If you go into the menu below. there is then an option to use beta versions.

![image](https://user-images.githubusercontent.com/29158690/133329003-415b137e-bbe8-4b63-b734-dba06ee8efea.png)

**Comment by bensmithuk** [comment]
I've tested with all the dimmers I have and it works as expected 👍

**Comment by paularnol** [comment]
Seems to have stopped syncing lights turned on in the lightwave app, not always showing until I reboot home assistant.

**Comment by gary-sargent** [comment]
Hi, I have 3.4.2-beta2 installed, and the click events for the lights are working. I tried it for the plug switches as you asked for, and no event is generated.

**Comment by bigbadblunt** [comment]
Does anyone know if the click events should work for sockets? Have the sockets got new firmware/is there a "multi press" tab in the app in the same way as for lights?

**Comment by bigbadblunt** [comment]
@paularnol I can't reproduce your problem. If it's still a problem can you open a new issue and send some log files please?

**Comment by gary-sargent** [comment]
> Does anyone know if the click events should work for sockets? Have the sockets got new firmware/is there a "multi press" tab in the app in the same way as for lights?

Yes they definitely support it I've tested it.

**Comment by bigbadblunt** [comment]
OK, in which case can you please turn on logging and send me a log file?

To enable additional logging, add the following to configuration.yaml

logger:
  default: warning
  logs:
    lightwave2.lightwave2: debug
    custom_components.lightwave2: debug
    custom_components.lightwave2.switch: debug
    custom_components.lightwave2.light: debug

Also a screenshot of the attributes from developer tools->state (like the one below)

![image](https://user-images.githubusercontent.com/29158690/133881756-5c448754-6f8d-40df-a3d1-b1cb6711b2de.png)

**Comment by gary-sargent** [comment]
Hi,

The logs produced when double clicking the left socket button were:

```
2021-09-18 11:21:16 DEBUG (MainThread) [lightwave2.lightwave2] consumer_handler: Received WSMessage(type=<WSMsgType.TEXT: 1>, data='{"version":1,"senderId":"1.ip=10=192=22=239*eu=west=1*compute*internal=66182","transactionId":13219166,"direction":"notification","class":"feature","operation":"event","items":[{"payload":{"time":1631960476339,"featureId":"610e7eb94ba41f668b77fe03-58-3157355974+1","deviceId":2,"type":"uiButton","channel":0,"writable":true,"stateless":true,"virtual":false,"value":258,"status":"ok"},"success":true,"itemId":1}]}', extra='')
2021-09-18 11:21:16 DEBUG (MainThread) [lightwave2.lightwave2] consumer_handler: Event received (610e7eb94ba41f668b77fe03-58-3157355974+1 uiButton 258), calling callbacks ['async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback']
2021-09-18 11:21:16 DEBUG (MainThread) [lightwave2.lightwave2] consumer_handler: Starting consumer handler
```

And the filter attributes are:

```
current_power_w: 4
lwrf_switch: 0
lwrf_outletInUse: 0
lwrf_protection: 0
lwrf_power: 4
lwrf_energy: 13378
lwrf_identify: 0
lwrf_reset: 0
lwrf_upgrade: 0
lwrf_diagnostics: 0
lwrf_periodOfBroadcast: 0
lwrf_rgbColor: 16711680
lwrf_voltage: 244
lwrf_error: 0
lwrf_socketSetup: 0
lwrf_current: 23
lwrf_uiButton: 258
lwrf_uiButtonPair: 0
lrwf_product_code: L42
friendly_name: Living Room Socket Left
```

**Comment by gary-sargent** [comment]
Change "uiButtonPair" to "uiButton" on line 62 of switch.py?

**Comment by gary-sargent** [comment]
Hi,

I tried the change above on my local instance and it works. I then get an event:

```{
    "event_type": "lightwave2.click",
    "data": {
        "entity_id": "switch.living_room_socket_left",
        "code": 258
    },
    "origin": "LOCAL",
    "time_fired": "2021-09-18T10:39:14.319622+00:00",
    "context": {
        "id": "68444575829627c5c30b96692390dc81",
        "parent_id": null,
        "user_id": null
    }
}
```
Looks like the code values are the same as the "up" buttons in the light switch.

**Comment by bigbadblunt** [comment]
Cool! I've just added a new release with this code change.

**Comment by gary-sargent** [comment]
Tested, works great. Thanks.

**Comment by bigbadblunt** [comment]
Thanks for your help.

**Comment by paularnol** [comment]
> @paularnol I can't reproduce your problem. If it's still a problem can you open a new issue and send some log files please?

I downgraded back to v3.2.2 for the moment. I’ll upgrade back to the beta though and test again. It seemed to raise the issue after an update on home assistant.
