### ISSUE TITLE
Not working in HA

### ISSUE THREAD

**Issue by Bod1973** [bigbadblunt/homeassistant-lightwave2#42]
Have followed the manual procedure, adding the 11x files into the folder as described.  Unfortunately am unable to find the Lightwave2 integration so unable to proceed.  Am a newbie so just need to confirm that I have correctly completed the procedure.

**Comment by bigbadblunt** [comment]
Did you also copy the translations folder and its contents?

It should look like

![image](https://user-images.githubusercontent.com/29158690/136648285-1aee8504-4330-4e9c-9048-53b3120b761f.png)

**Comment by bigbadblunt** [comment]
You will at least need to restart Home Assistant. The file structure is in an app called WinSCP.

**Comment by Bod1973** [comment]
Thanks. 
I am not 100% sure that I have created the folders in the right root folder as using the File Editor in HA. H9w would i install WinSCP?
--
Sent from Outlook Email App for Android Saturday, 09 October 2021, 07:30pm +01:00 from bigbadblunt  ***@***.*** :

**Comment by bigbadblunt** [comment]
PS I have no idea what you're running home assistant on. I am running it on a linux server.

**Comment by Bod1973** [comment]
Sorry. Home Assistant is running on a RPi4 which I access over ip
--
Sent from Outlook Email App for Android Saturday, 09 October 2021, 07:43pm +01:00 from bigbadblunt  ***@***.*** :

**Comment by bigbadblunt** [comment]
Winscp is a Windows app that you can use to see the files on your rpi, and transfer files to/from the rpi.

**Comment by Bod1973** [comment]
Thanks very much for your assistance. I assume that you are also in the UK?
--
Sent from Outlook Email App for Android Sunday, 10 October 2021, 08:51am +01:00 from bigbadblunt  ***@***.*** :

**Comment by Bod1973** [comment]
Thanks for your efforts. 
I flashed HA onto the SD card from  home-assistant.io/installation/raspberrypi

--
Sent from Outlook Email App for Android Sunday, 10 October 2021, 10:44am +01:00 from bigbadblunt  ***@***.*** :

**Comment by bigbadblunt** [comment]
Ah, ok. I definitely have no idea how that installation works. I suggest https://community.home-assistant.io/ and see if they can help with how to install custom components.

**Comment by bigbadblunt** [comment]
I can't see your attachment, but if there are two fields it should be username and password.
