### ISSUE TITLE
Lightwave heating devices showing up incorrectly (Lightwave L92 and Honeywell HR91 / DTS92E)

### ISSUE THREAD

**Issue by dhardiker** [bigbadblunt/homeassistant-lightwave2#46]
Hi!

I'm an experienced programmer (Java/Javascript mostly, but I just about know my way around Python) and I've been adding home automation systems for about a decade now. I'm about 6 months into my Lightwave journey with lots of devices and have just added Home Assistant to get a better control plane and create more advanced automation logic. I also don't like my usage data being locked up in the Lightwave (and many other) apps.

I've been getting on pretty well with lighting and power sockets, your custom component pulled them all in brilliantly. Thanks for sharing - it's really done a bunch of the work for me already!

However, I have come unstuck with using the Lightwave heating devices in Home Assistant. I'm fairly new to Home Assistant, and am happy to contribute (but will need a bit of support to make any PR useful).

# Relevant Devices

I have a bunch of radiators in my property, each fitted with a [Honeywell TRV (HR91)](https://shop.lightwaverf.com/collections/all/products/trv-hr91). My central heating system is zoned into 3 loops, each individually controlled by a [Smart Heating Switch (L92)](https://shop.lightwaverf.com/collections/all/products/l92-smart-switch). I also have a couple of [Honeywell Home Wireless Thermostats (DTS92E)](https://shop.lightwaverf.com/collections/all/products/honeywell-home-thermostat) for some rooms with underfloor heating.

I have connected them all appropriately within a Lightwave automation to call for heat, which is pretty functional. However the Lightwave App is really restricted. So if I have 10 TRVs connected to a L92, it's very tedious to work out which TRVs are causing the heating to be on - as you have to go into each room and drill into the TRV to find out if it's actively calling-for-heat or not. So, dragging all that information into Home Assistant will enable me to create a better control plane.

Notably, the devices are appearing in Home Assistant in an incorrect / illogical manner.

# Representation in the Lightwave App

## HR91
Within the Lightwave App the HR91s show:
* Temperature (degrees centigrade to 1dp)
* Valve open status (percentage)
* Battery (percentage)

With two control tabs:
* Target Temperature Slider (degrees centigrade to 1dp)
* "State" (binary) with text reading "Setting the state to 'off' will cause the device to target 5 degrees. Setting the state to 'on' will cause the device to target 21 degrees" ... these are universally off on my TRVs

## L92
Within the Lightwave App the L92s show:
* Temperature (degrees centigrade to 1dp) - around the L92, not that useful to me as it's sat next to my boiler!
* Humidity (percentage to 1dp)
* Watts consumption
* kWattHours total

With 4 control tabs:
* "State" (binary) - for manually turning the heating control on/off, useful for my hot water circulator and hot water heater, but not so much for central heating which is driven by the heat demand from the TRVs
* Target (degrees centigrade to 1dp) - not useful to me, as it's set against the temperature of the L92
* Boost (binary I presume) - not used this yet, I just see "setup boost function"
* Lock (binary) - disables the hardware controls for the L92

## DTS92E
I also have two Honeywell Home Wireless Thermostats (DTS92E) which show up in the app:
* Temperature (degrees centigrade to 1dp)
* Battery (percentage)

With one control tab:
* Target Temperature Slider (degrees centigrade to 1dp)

# Representation in Home Assistant

## HR91
If I go to `Configuration > Devices` then I can see all my TRVs - although they show the model up as `HR92` rather than `HR91`. It does not show the battery level, just a dash. When I click into the device, it shows me a single item under `Entities` marked `Closed` and if I drill down again, I see it has the entity ID of `binary_sensor.office_trv`.

## L92
If I go to `Configuration > Devices` then I can see all my L92s, with the correct model, no battery (as it's wired that's fine), with 4 entities:
* `switch.central_heating_l92`
* `sensor.central_heating_l92_current_consumption`
* `lock.central_heating_l92_lock`
* `sensor.central_heating_l92_total_consumption`

Missing is humidity, current temperature, target temperature, or anything related to boost (which might be as I've not set boost up).

## DTS92E
I am unable to find anything under Devices or Entities which looks like the thermostats, nor anything with the name thermostat (as they're named in the Lightwave app). They were only added in the last 24 hours, I'm not sure if they would appear automatically.

# Finally - the request!

Hopefully the above context helps. From what little I've picked up about Lightwave's web socket data structure, Home Assistant's API and what your custom component is doing, it seems like:

* The HR91 is being given only a single `binary_sensor` entity, which I guess represents the "State" (that is always off for me) and needs expanding for the other 4 entities.
* The L91s have 4 of the entities already, but are missing humidity, current temperature, target temperature, or anything related to boost.
* The DTS92Es aren't being detected at all for some reason (which might be because I need to update/refresh something for them to appear).

With some tips I'm up for helping out - to do so, some hints on where to start in the cod, how to deploy a development version (I'm currently using HACS), and what the dev/debug loop looks like, would all be of great help!

Alternatively, if it's something easy to change, perhaps with a bit more information from me, I'll happily provide.

**Comment by bigbadblunt** [comment]
Hi @dhardiker 

The easiest way to get started is to turn on debug logging and you to send me the logs from a restart. On restart the component read all of the "features" exposed by lightwave, then it should just be a case of me trying to map these onto Ha's interface.

If you're on the latest version of the component, you can turn logging on through the integrations page of the web interface (go into the options for the lightwave 2 component). Then restart ha, and send me the logs.

**Comment by bigbadblunt** [comment]
There are a couple of lines at the start that show a one time access token. These should be pretty obvious, you can delete them.

**Comment by dhardiker** [comment]
I've redacted the token & personal information. It's pretty big so I've [put it onto Dropbox](https://www.dropbox.com/s/faf3ra7lzw2bly2/docker.homeassistant-20211021-220700.log?dl=0) - I'll remove once you confirm you've got what you need.

Sorry about the needle in the haystack, I've got rather a large number of Lightwave devices. Let me know if I can provide anything else.

**Comment by bigbadblunt** [comment]
@dhardiker Happy to close this one?

**Comment by dhardiker** [comment]
Ah sorry! Yes. Totally should have done that. I've been distracted building sensors to get more data into Home Assistant (notably temperature sensors I can strap to heating pipes to see where the pipes get hot / not).

I'm sure I'll be back but I'm happy to reopen / open up more issues as needs be.

Thanks again for your swift help!

**Comment by bigbadblunt** [comment]
Yes, please do open another issue if you spot anything wrong, or just suggestions for improvement.
