### ISSUE TITLE
Support entity categorization

### ISSUE THREAD

**Issue by gary-sargent** [bigbadblunt/homeassistant-lightwave2#47]
HA 2021.11 adds entity categorization. Are you able to add support for this please?

For example button locks and LED entities could be "configuration" entities.

See: https://www.home-assistant.io/blog/2021/11/03/release-202111/#entity-categorization

**Comment by bigbadblunt** [comment]
Yeah, looks reasonably straightforward. Give me a few days.

**Comment by bigbadblunt** [comment]
Just pushed a new release. Let me know if it works for you.

**Comment by gary-sargent** [comment]
Works great thanks.

Not sure if plug socket plugged in detection should be a sensor (as is) or diagnostic to be more consistent with others. It's currently appearing on the default lovelace dashboard which I doubt is much use.

**Comment by bigbadblunt** [comment]
Ooops, I missed the plug sensor. I suspect I've also broken some of the other sensors (things like energy monitors). Let me have another go.

**Comment by bigbadblunt** [comment]
Thank. I have changed the plug sensor to "diagnostic" (btw, can you confirm this works? I don't have any gen 2 sockets).

I also reverted the classification of energy sensors from "diagnostic" to none. I think this is how they should appear. But I also have no energy monitors, so no way of testing that either.

**Comment by gary-sargent** [comment]
Hi,

Looks good, and yes the sensor works.

The only one that looks wrong is the sensor for current which is showing values like 24 amps which can not be right for a 13amp socket!

**Comment by bigbadblunt** [comment]
OK - if you could compare the output from HA to what's in the app then maybe it'll be obvious what the problem is. I suspect the values are to 1 decimal place (i.e. should be 2.4 amps). If you can confirm, then I can update.

**Comment by gary-sargent** [comment]
Current is not listed in the app, but experimenting it looks like the value you are showing is mA not A, so needs dividing by 1000 to show the right value in A, or units changing to mA. That said, I'm not sure it is that useful to have it at all as Amps can be derived from Power (watts) and Voltage using A=P/V

**Comment by bigbadblunt** [comment]
Updated to be in mA.

**Comment by gary-sargent** [comment]
Works great. Thanks, feel free to close this ticket.

**Comment by bigbadblunt** [comment]
Thanks @gary-sargent, and thanks for the feedback/testing. I only have a couple of bits of lightwave kit so it's a bit hit-and-miss developing for things I don't have, it's really useful to get good, clear feedback and results.

Let me know if you have any future suggestions.
