### ISSUE TITLE
Invalid config

### ISSUE THREAD

**Issue by jezza10d** [bigbadblunt/homeassistant-lightwave2#5]
I am trying to load the lightwave2 config and I have added the security and component in the yammer file. I am still getting the following response

![image](https://user-images.githubusercontent.com/55980878/65871395-3537b480-e376-11e9-90ad-9a28266713d0.png)

_

> Invalid config
> The following components and platforms could not be set up:
> 
> lightwave2
> Please check your config.

_

I am also getting the following logs

Log Details (ERROR)
Mon Sep 30 2019 11:25:54 GMT+0100 (British Summer Time)
Error during setup of component lightwave2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 168, in _async_setup_component
    hass, processed_config
  File "/config/custom_components/lightwave2/__init__.py", line 35, in async_setup
    from custom_components.lightwave2 import lightwave2
ImportError: cannot import name 'lightwave2' from 'custom_components.lightwave2' (/config/custom_components/lightwave2/__init__.py)

This was working around a week ago but then it stopped working. Since then I have tried everything including fresh installs of the component and even home assistant.

Home assistant is working on a docker within synology and other custom components are loading and working fine.

**Comment by MightyJudge** [comment]
Have you pulled the latest changes recently? I had the same issue and noticed @bigbadblunt had made a change in order to deal with the fact lightwave is sending a slightly different response.

Pulling the changes solved the issue for me.

**Comment by jezza10d** [comment]
Hi @MightyJudge , 

Yes i am afraid i have tried. I have been trying a few different ways since yesterday's update. I am wondering if i am missing something my side still as it doesn't seem anyone else is currently facing the issue but i have exhausted all things i can think of. I am happy to hear any other ideas floating around.

**Comment by MaxIsMyName** [comment]
I have the same issue. Reverting this [commit](https://github.com/bigbadblunt/homeassistant-lightwave2/commit/6fa45c15aeca0f7660f07f4372e7f142c348df37) fixes the issue. Ie, deleting the custom_compenents. part.

**Comment by jezza10d** [comment]
@MaxIsMyName thank you so much. Now working again!!
Really appreciate your input

**Comment by bigbadblunt** [comment]
Reopening until I work out if I need to fix.
