### ISSUE TITLE
Changing name in Lightwave App does not pull through

### ISSUE THREAD

**Issue by dhardiker** [bigbadblunt/homeassistant-lightwave2#50]
Hi Again!

I've recently zoned my central heating piping and turned my single [L92 Smart Switches](https://shop.lightwaverf.com/products/l92-smart-switch) into a triple to control the zones independently. This means I've renamed my "Central Heating L92" in the app to "Upstairs Heat L92" and added new "Downstairs Left Heat L92" and "Downstairs Right Heat L92" devices. Initially they didn't show up, but after a restart of Home Automation they did - however the renamed one remains "Central Heating L92" throughout (the entity system name is still "climate.central_heating_l92").

I've found a "Friendly Name" property on the entity, but it doesnt seem to have updated along with the app.

![Screenshot 2021-11-18 at 22 14 52](https://user-images.githubusercontent.com/348522/142505406-fc860d6f-5814-4a96-946d-813bce334477.png)

I'm thinking the solution to clean up the entity system name will need to be to unpair it from the Lightwave system and repair it with the new name, but I think the updated Friendly Name should certainly pull through.

**Comment by bigbadblunt** [comment]
Friendly name isn't set by the component, it's set by the user in the entity properties dialog.

![image](https://user-images.githubusercontent.com/29158690/142727668-42984aa9-5d50-4dbb-8cf8-f7d85b09dde4.png)

In the name box here, if you don't type anything, HA auto-assigns a friendly name based on the entity id. Or you can enter your own name which will overrule the auto-assigned named.

You can also manually change the entity_id here.

I don't want to change the entity_ids based on changes made in the app. The would break any automations/UI that have been configured based on the previous entity_ids. I actually don't think I even can change - the new names assigned in the app don't seem to be provided by the server, so at the moment I can't see them even if I wanted to change the behaviour.
