### ISSUE TITLE
Heating use case question

### ISSUE THREAD

**Issue by eoinverling** [bigbadblunt/homeassistant-lightwave2#51]
Not so much a bug with your code, but with my understanding

I have a bunch of LW gear, mostly the older Connect Series, recently upgraded to the L2 controller .. so now trying to setup my heating in HA. I have

LW921 - Thermostat
LW920 - Boiler Switch

Previously, I set the schedule in the LW921 (via older Connect App) and it controlled the LW920 to turn on/off the boiler.

Questions
1. Do I just add all the devices within the new Smart LW App, and NO heating schedule automation, set all the scheduling within HA?
2. Will the link between the LW921 and LW920 no longer be needed, as HA will directly connect to LW920 to turn it on/off? ie LW921 is "just" a thermostat and LW920 is "just" a switch ?

thanks
e

**Comment by bigbadblunt** [comment]
I don't know! I only have an LW934, and I use the built-in thermostat (it's controlling a electric radiator).

You definitely need to add the devices to the Smart app and get them working there. Then let's see how they turn up in HA. I'm hopeful they'll turn up as a single "climate" entity, but let me know what you see in the Configuration->Integrations->Lightwave entities page once they're set up.

**Comment by eoinverling** [comment]
Here's what the entities look like:-


![Screenshot 2021-11-25 at 14 15 41](https://user-images.githubusercontent.com/4394979/143457179-49fb11c1-e77f-4b0f-be6b-e098af0bbf5f.png)
![Screenshot 2021-11-25 at 14 14 58](https://user-images.githubusercontent.com/4394979/143457184-5127d352-f224-443b-aa12-2bdd93a88fdf.png)


![Screenshot 2021-11-25 at 14 08 02](https://user-images.githubusercontent.com/4394979/143456821-81774222-4119-4704-ba05-fd0cbaa1b15b.png)
![Screenshot 2021-11-25 at 14 07 32](https://user-images.githubusercontent.com/4394979/143456825-fc32264a-6bb1-49e1-a636-55ccacaf484b.png)

**Comment by bigbadblunt** [comment]
PS if you add climate.thermostat to your UI, you should get a card like this

<img width="304" alt="image" src="https://user-images.githubusercontent.com/29158690/143458919-1d708380-14be-46f7-9a87-dcac843fab69.png">

**Comment by eoinverling** [comment]
So it seems to be doing what it's supposed to be! :)

I have a schedule in the LW app, the history seems to reflect that it is true/working. So my next test should be remove the schedule from LW app and do that within HA?

Also, generic HA question ... if I want to add configuration for the thermostat, eg set the `min_temp` and `max_temp`, do I just add a  `climate` section in the configuration.yml .. or is there an already auto-generated config somewhere?


<img src="https://user-images.githubusercontent.com/4394979/143467480-eafcd98c-f8ae-4d83-8ae5-29f1ce9dc55a.png" width=40% height=40%>

<img src="https://user-images.githubusercontent.com/4394979/143467483-e8b18eb4-3307-4542-8c03-6cd44b98d3ac.png" width=40% height=40%>

<img src="https://user-images.githubusercontent.com/4394979/143467487-fb5a12f3-4bc8-4a74-88aa-c221756c2f78.png" width=100% height=50%>

<img src="https://user-images.githubusercontent.com/4394979/143467492-47e06792-3ee0-4644-b3ad-5da0555aed7c.jpg" width=30% height=30%>

**Comment by bigbadblunt** [comment]
Cool.

There is no config that can be changed. The min and max temps are hard coded to 0 and 40C respectively (this matches what's in the LW app).

Up to you whether you set the schedule in the app or in HA.  If you do it in HA, then you just need a call to `climate.set_temperature`.
