### ISSUE TITLE
2021.12 - implements device_state_attributes. Please report it to the custom component author.

### ISSUE THREAD

**Issue by B-Hartley** [bigbadblunt/homeassistant-lightwave2#52]
in Home Assistant 2021.12
the following error is produced in the log:

`2021-12-10 21:07:37 WARNING (MainThread) [homeassistant.helpers.entity] Entity light.kitchen_ceiling_4 (<class 'custom_components.lightwave2.light.LWRF2Light'>) implements device_state_attributes. Please report it to the custom component author.`

As per Home Assistant 2021.12b0, the usage of device_state_attributes is depricated. I think extra_state_attributes should be used from now on (see the Home Assistant Github Beta channel for more info).

**Comment by bigbadblunt** [comment]
Thanks! Should be fixed now]

https://github.com/bigbadblunt/homeassistant-lightwave2/releases/tag/v3.5.8
