### ISSUE TITLE
Cannot setup

### ISSUE THREAD

**Issue by RageInvader** [bigbadblunt/homeassistant-lightwave2#54]
After installing via HACS and adding integration i'm getting this error after I log in and it says its setup.

Tried looking online but cannot find anyone with a solution.

>This error originated from a custom integration.
>
>Logger: homeassistant.config_entries
>Source: custom_components/lightwave2/__init__.py:117
>Integration: Lightwave v2 (Smart Series) custom component (documentation)
>First occurred: 22:54:50 (1 occurrences)
>Last logged: 22:54:50
>
>Error setting up entry **********@gmail.com for lightwave2
>Traceback (most recent call last):
>  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
>    result = await component.async_setup_entry(hass, self)  # type: ignore
>  File "/config/custom_components/lightwave2/__init__.py", line 117, in async_setup_entry
>    await link.async_get_hierarchy()
>  File "/usr/local/lib/python3.9/site-packages/lightwave2/lightwave2.py", line 230, in async_get_hierarchy
>    await self.async_update_featureset_states()
>  File "/usr/local/lib/python3.9/site-packages/lightwave2/lightwave2.py", line 267, in async_update_featureset_states
>    x.features[y][1] = value["items"][0]["payload"]["value"]
>KeyError: 'payload'

**Comment by bigbadblunt** [comment]
This may well be a temporary glitch. Can you restart your HA server and see if that helps?

If not can you turn on additional logging, restart and give me the output?

If the integration has installed correctly, then you can go to `[your url]/config/integrations` and turn on through the ui

![image](https://user-images.githubusercontent.com/29158690/146668598-bd106e6a-1f66-4999-9091-2825b3f09f76.png)

If that's not available, you'll need to add the following to your configuration.yaml:

```
logger:
  default: warning
  logs:
    lightwave2.lightwave2: debug
    custom_components.lightwave2: debug
```

**Comment by RageInvader** [comment]
Have restarted several times previously, done it again though resetup the integration, enabled debug logs and still getting errors. Here the log, is it related to the Template variable warning?

> 2021-12-19 09:01:38 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'entity_id' when rendering '{%- if target_lights.entity_id is string -%}
> {{ [target_lights.entity_id] }}
> {%- else -%}
> {{ target_lights.entity_id }}
> {%- endif -%}'
> 2021-12-19 09:03:38 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'entity_id' when rendering '{%- if target_lights.entity_id is string -%}
> {{ [target_lights.entity_id] }}
> {%- else -%}
> {{ target_lights.entity_id }}
> {%- endif -%}'
> 2021-12-19 09:04:39 DEBUG (MainThread) [lightwave2.lightwave2] consumer_handler: Received WSMessage(type=<WSMsgType.CLOSE: 8>, data=1000, extra='')
> 2021-12-19 09:04:39 DEBUG (MainThread) [lightwave2.lightwave2] consumer_handler: Starting consumer handler
> 2021-12-19 09:04:39 DEBUG (MainThread) [lightwave2.lightwave2] consumer_handler: Received WSMessage(type=<WSMsgType.CLOSED: 257>, data=None, extra=None)
> 2021-12-19 09:04:39 INFO (MainThread) [lightwave2.lightwave2] consumer_handler: Websocket closed in message handler
> 2021-12-19 09:04:39 INFO (MainThread) [lightwave2.lightwave2] consumer_handler: Websocket reconnect requested by message handler
> 2021-12-19 09:04:39 DEBUG (MainThread) [lightwave2.lightwave2] consumer_handler: Starting consumer handler
> 2021-12-19 09:04:39 DEBUG (MainThread) [lightwave2.lightwave2] consumer_handler: websocket not ready, sleeping for 1 sec
> 2021-12-19 09:04:39 DEBUG (MainThread) [lightwave2.lightwave2] connect_to_server: Connecting to websocket
> 2021-12-19 09:04:40 DEBUG (MainThread) [lightwave2.lightwave2] get_access_token_username: Requesting authentication token (using username and password)
> 2021-12-19 09:04:40 DEBUG (MainThread) [lightwave2.lightwave2] consumer_handler: Starting consumer handler
> 2021-12-19 09:04:49 DEBUG (MainThread) [custom_components.lightwave2.config_flow] Creating options form using existing options: {'lightwave_publicapi': False, 'lightwave_debug': True}
> 2021-12-19 09:05:38 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'entity_id' when rendering '{%- if target_lights.entity_id is string -%}
> {{ [target_lights.entity_id] }}
> {%- else -%}
> {{ target_lights.entity_id }}
> {%- endif -%}'
> 2021-12-19 09:07:38 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'entity_id' when rendering '{%- if target_lights.entity_id is string -%}
> {{ [target_lights.entity_id] }}
> {%- else -%}
> {{ target_lights.entity_id }}
> {%- endif -%}'
> 2021-12-19 09:09:38 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'entity_id' when rendering '{%- if target_lights.entity_id is string -%}
> {{ [target_lights.entity_id] }}
> {%- else -%}
> {{ target_lights.entity_id }}
> {%- endif -%}'
> 2021-12-19 09:09:40 DEBUG (MainThread) [lightwave2.lightwave2] consumer_handler: Received WSMessage(type=<WSMsgType.CLOSE: 8>, data=1000, extra='')
> 2021-12-19 09:09:40 DEBUG (MainThread) [lightwave2.lightwave2] consumer_handler: Starting consumer handler
> 2021-12-19 09:09:40 DEBUG (MainThread) [lightwave2.lightwave2] consumer_handler: Received WSMessage(type=<WSMsgType.CLOSED: 257>, data=None, extra=None)
> 2021-12-19 09:09:40 INFO (MainThread) [lightwave2.lightwave2] consumer_handler: Websocket closed in message handler
> 2021-12-19 09:09:40 INFO (MainThread) [lightwave2.lightwave2] consumer_handler: Websocket reconnect requested by message handler
> 2021-12-19 09:09:40 DEBUG (MainThread) [lightwave2.lightwave2] consumer_handler: Starting consumer handler
> 2021-12-19 09:09:40 DEBUG (MainThread) [lightwave2.lightwave2] consumer_handler: websocket not ready, sleeping for 1 sec
> 2021-12-19 09:09:40 DEBUG (MainThread) [lightwave2.lightwave2] connect_to_server: Connecting to websocket
> 2021-12-19 09:09:40 DEBUG (MainThread) [lightwave2.lightwave2] get_access_token_username: Requesting authentication token (using username and password)
> 2021-12-19 09:09:41 DEBUG (MainThread) [lightwave2.lightwave2] consumer_handler: Starting consumer handler
> 2021-12-19 09:11:38 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'entity_id' when rendering '{%- if target_lights.entity_id is string -%}
> {{ [target_lights.entity_id] }}
> {%- else -%}
> {{ target_lights.entity_id }}
> {%- endif -%}'
> 2021-12-19 09:13:38 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'entity_id' when rendering '{%- if target_lights.entity_id is string -%}
> {{ [target_lights.entity_id] }}
> {%- else -%}
> {{ target_lights.entity_id }}
> {%- endif -%}'
> 2021-12-19 09:14:40 DEBUG (MainThread) [lightwave2.lightwave2] consumer_handler: Received WSMessage(type=<WSMsgType.CLOSE: 8>, data=1000, extra='')
> 2021-12-19 09:14:40 DEBUG (MainThread) [lightwave2.lightwave2] consumer_handler: Starting consumer handler
> 2021-12-19 09:14:40 DEBUG (MainThread) [lightwave2.lightwave2] consumer_handler: Received WSMessage(type=<WSMsgType.CLOSED: 257>, data=None, extra=None)
> 2021-12-19 09:14:40 INFO (MainThread) [lightwave2.lightwave2] consumer_handler: Websocket closed in message handler
> 2021-12-19 09:14:40 INFO (MainThread) [lightwave2.lightwave2] consumer_handler: Websocket reconnect requested by message handler
> 2021-12-19 09:14:40 DEBUG (MainThread) [lightwave2.lightwave2] consumer_handler: Starting consumer handler
> 2021-12-19 09:14:40 DEBUG (MainThread) [lightwave2.lightwave2] consumer_handler: websocket not ready, sleeping for 1 sec
> 2021-12-19 09:14:40 DEBUG (MainThread) [lightwave2.lightwave2] connect_to_server: Connecting to websocket
> 2021-12-19 09:14:40 DEBUG (MainThread) [lightwave2.lightwave2] get_access_token_username: Requesting authentication token (using username and password)
> 2021-12-19 09:14:41 DEBUG (MainThread) [lightwave2.lightwave2] consumer_handler: Starting consumer handler
> 2021-12-19 09:15:38 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'entity_id' when rendering '{%- if target_lights.entity_id is string -%}
> {{ [target_lights.entity_id] }}
> {%- else -%}
> {{ target_lights.entity_id }}
> {%- endif -%}'

**Comment by bigbadblunt** [comment]
This is a different problem than before - this looks like wrong username or password.

Can you log in to https://my.lightwaverf.com/a/login ?

**Comment by RageInvader** [comment]
Hi yes I can login using same username and password, I had thought maybe it was that and logged out and back in app to check I had correct login.

**Comment by bigbadblunt** [comment]
The first error you provided was definitely getting past the login stage. This seems to have now changed and be hanging at the login stage. Can you delete and re-enable the integration?

**Comment by RageInvader** [comment]
so after removing, restarting server and re-adding the integration, I'm getting the first error again, I enabled the debug logs restarted server and its now outputted a massive log.

[halog-1833.txt](https://github.com/bigbadblunt/homeassistant-lightwave2/files/7741337/halog-1833.txt)

**Comment by bigbadblunt** [comment]
Great! That's progress. I can fix this, but I'm not sure why it happens. 

It looks like you have two LinkPlus hubs in your account, and one of them is unreachable?

**Comment by bigbadblunt** [comment]
OK, I've just released a new (beta) version, let me know if it works.

https://github.com/bigbadblunt/homeassistant-lightwave2/releases/tag/v3.5.10beta

You may have to enable beta versions in HACS

![image](https://user-images.githubusercontent.com/29158690/146688293-1876c27e-88e9-4174-a615-4eb6b3302027.png)
![image](https://user-images.githubusercontent.com/29158690/146688297-51816e33-963e-46df-95d4-9db3a0867064.png)

**Comment by RageInvader** [comment]
> It looks like you have two LinkPlus hubs in your account, and one of them is unreachable?

I do have two one, is an old one that failed. never even thought of that.

ur a hero its working now. thanks v much
