### ISSUE TITLE
Setting up a group of TRV's

### ISSUE THREAD

**Issue by AngloYorkshire** [bigbadblunt/homeassistant-lightwave2#57]
I want to set up a group of my TRV's at a set temperature so that when I am on my way home (and others) they change to the relevant temperature set and then if heating is required the Call For Heat will turn on my boiler.

The trouble is setting up the temperatures for each individual radiator but when I set the desired temperature, it reverts to the current desired temperature I have set on the app as it has read the app.

I need to be able to set the temperatures independently of what it is at the moment but at the moment it is not possible.

Thanks

**Comment by bigbadblunt** [comment]
Can you describe more how you are trying to set the target temperature for the trvs please?

**Comment by AngloYorkshire** [comment]
Hi,When I am setting a scene where I am adding my TRV’s together so I can include them in an automation I put them in a group (scene) and try to set each individual temperature, but I cannot save it then and it automatically goes back to what it is already set to go to. I cannot save it at that temperature.See image included.Hope this helpsMatthew  Sent from Mail for Windows From: bigbadbluntSent: 19 January 2022 06:58To: bigbadblunt/homeassistant-lightwave2Cc: AngloYorkshire; AuthorSubject: Re: [bigbadblunt/homeassistant-lightwave2] Setting up a group of TRV's (Issue #57) Can you describe more how you are trying to set the target temperature for the trvs please?—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by bigbadblunt** [comment]
Hi, the picture is not showing

**Comment by AngloYorkshire** [comment]
Hope this works. Matthew Sent from Mail for Windows From: bigbadbluntSent: 20 January 2022 08:09To: bigbadblunt/homeassistant-lightwave2Cc: AngloYorkshire; AuthorSubject: Re: [bigbadblunt/homeassistant-lightwave2] Setting up a group of TRV's (Issue #57) Hi, the picture is not showing—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by bigbadblunt** [comment]
No, hasn't worked. You might have to do this on github.

**Comment by AngloYorkshire** [comment]
Hi,Thanks anyway, but found a work around using Climate Groups and fingers crossed it is working correctly so far.Many thanks for everything Matthew Sent from Mail for Windows From: bigbadbluntSent: 20 January 2022 17:58To: bigbadblunt/homeassistant-lightwave2Cc: AngloYorkshire; AuthorSubject: Re: [bigbadblunt/homeassistant-lightwave2] Setting up a group of TRV's (Issue #57) No, hasn't worked. You might have to do this on github.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>
