### ISSUE TITLE
Integration not removing devices that have been removed from Lightwave App

### ISSUE THREAD

**Issue by alexhassdev** [bigbadblunt/homeassistant-lightwave2#58]
**Describe the bug**
I'm going through a remodel of my house so have removed some lightswitches from the lightwave app (after resetting them), they will probably be reused elsewhere, but for now I thought it was best to remove them.

However, this integration doesn't seem to have the functionality that was added to home assistant to remove old devices (See https://github.com/dermotduffy/hass-motioneye/blob/c97e4056914c616458284633e4a8a3480e98700e/custom_components/motioneye/__init__.py#L380-L389) 
**To Reproduce**
Delete a device from the lightwave app and restart HA
**Expected behavior**
Removed devices should be removed from HA

**Comment by bigbadblunt** [comment]
Thanks so much for the link, I've released a new version that should do what you suggest.

I also learned about for:else!

**Comment by alexhassdev** [comment]
No, thank you for implementing so fast!

I've installed the beta and all looks good!

`[36m2022-01-27 18:35:51 DEBUG (MainThread) [custom_components.lightwave2] Identifier not matched, removing device\u001b[0m","source":"stderr","tag":"ghcr.io/home-assistant/raspberrypi4-homeassistant:2021.12.2/homeassistant/f19cf6bf7c9a"`
