### ISSUE TITLE
Unstable multi press

### ISSUE THREAD

**Issue by robcos** [bigbadblunt/homeassistant-lightwave2#59]
I was wondering if "it is just me" but I have seen multi press events not being very reliable. Restarting HA and/or NodeRed seems to fix it. What's a good way of debugging what is going on?

(Thank you so much for this support - Multi taps are so cool...I can for example start the music in a room when I dbl tap up or turn off all lights on a floor if I triple tap down)

**Comment by bigbadblunt** [comment]
If you turn on debug logging, then next time you get an unreliable multi-press, can you:

1) check that the lightwave app registered the multipress (the following screen in the app)

![image](https://user-images.githubusercontent.com/29158690/152695650-e500ba8b-de4a-4194-b937-e0dbad556cd7.png)

2) if it has registered in the app, but not in HA, send me the log

**Comment by bigbadblunt** [comment]
PS given that you say a restart fixes it, seems pretty certain it's a problem with HA not the actual device. So send me the logs. Might be that the connection to the lightwave servers is dropping.

**Comment by bigbadblunt** [comment]
I added a bit more debugging code to the component, which should log a message if there is a button press event.

**Comment by alexhassdev** [comment]
I've personally not seen any issues, I have quite a few automations based on multi press now and they seem to work all the time

**Comment by robcos** [comment]
I've noticed that the flakiness seems to be related to the hub not being close enough to some of the switches. I've relocated it - let's see how it goes! I'm going to close this in the meanwhile
