### ISSUE TITLE
Feature requests: set LED colour and receive state notifications for off -> off or on -> on.

### ISSUE THREAD

**Issue by MaxIsMyName** [bigbadblunt/homeassistant-lightwave2#6]
Apologies for the title.

I was wondering if the Lightwave Gen 2 switches allows broadcasting of switch press events that don't change the state of the lights. eg, if the lights are off but I press the off button again, I'd like to receive the event. 

There's also the possibility of setting the LEDs colour and brightness. Is that something the API allows?

**Comment by bigbadblunt** [comment]
The first one isn't possible. The server doesn't send any messages if the state isn't changing.

For the second one, do you mean the LED on the switches? Looks like it is possible. I'm not sure the best way to expose this to Home Assistant. Let me think.

**Comment by MaxIsMyName** [comment]
I have figured a way around the first one, I know simply set the state to on whenever another light is on (I have a dual gang switch with one of the gangs not connected to lights and used as a trigger for automations). 

The second, by cheating and declaring the switches as coloured lights to HA might be an option, however I have no idea if that’s possible. 

Do you also know if it’s possible to receive double click events? 

Appreciate your time mate, I’m ok in python but unfamiliar with the HA environment and struggling to find documentation.

**Comment by bigbadblunt** [comment]
Yeah, the documentation is a bit of a struggle. I tend to just browse the code for one of the official components, but that's a bit hit and miss.

Anyway, I've pushed a new version, which exposes the LED rgb colour as an attribute you can read, and also provide a service lightwave2.set_led_rgb which you can use to set the colour. Let me know if it works for you.

**Comment by bigbadblunt** [comment]
Sorry, forgot to ask - what does double click do?
