### ISSUE TITLE
Lost entities

### ISSUE THREAD

**Issue by joedowling23** [bigbadblunt/homeassistant-lightwave2#63]
Hiya

Since updating HA to 2022.4.0 I have lost all of the entities on my lightwave (led, power consumption etc) except the actual light itself. Don’t know if anyone else has found similar

Cheers

**Comment by bigbadblunt** [comment]
Suspect this is the same as #64

**Comment by joedowling23** [comment]
Thankyou very much - fixed in your updated code. Again many thanks do let me know if you have a 'Buy me a coffee' link!
