### ISSUE TITLE
2022.4.x almost all entities marked as "restored" but never recover after upgrade

### ISSUE THREAD

**Issue by SGXander** [bigbadblunt/homeassistant-lightwave2#66]
Hi, Updated to 2022.4.1 and then rolled back because of this issue, just tried again to 2022.4.4 and it's still the same. Bar the main switch and light entities, all other entities (voltage, LED, Lock etc) are in a restored state after the update and will not recover.

**Comment by bigbadblunt** [comment]
Are you using the latest beta version of the component? If so, can you turn on logging and send me some logs please?

**Comment by SGXander** [comment]
Hey @bigbadblunt sorry I didn't see the beta branch releases and was still on 3.5.10. confirmed all working again after updating to beta 3.5.13!
