### ISSUE TITLE
update_featureset_states: failed to read feature in HA 2022.4 with Lightwave RF v3.5.13 HACS plugin

### ISSUE THREAD

**Issue by bje** [bigbadblunt/homeassistant-lightwave2#67]
Hello,

Following an upgrade to `homeassistant/home-assistant:2022.4` with Lightwave RF `v3.5.13` HACS plugin, I'm getting the following traceback in my HA logs:

```
home-assistant                  | Traceback (most recent call last):
home-assistant                  |   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
home-assistant                  |     result = await component.async_setup_entry(hass, self)
home-assistant                  |   File "/config/custom_components/lightwave2/__init__.py", line 45, in async_setup_entry
home-assistant                  |     await link.async_get_hierarchy()
home-assistant                  |   File "/usr/local/lib/python3.9/site-packages/lightwave2/lightwave2.py", line 223, in async_get_hierarchy
home-assistant                  |     await self.async_update_featureset_states()
home-assistant                  |   File "/usr/local/lib/python3.9/site-packages/lightwave2/lightwave2.py", line 269, in async_update_featureset_states
home-assistant                  |     _LOGGER.warning("update_featureset_states: failed to read feature ({}), returned {}".format(x.features[y][0], value))
home-assistant                  | KeyError: <lightwave2.lightwave2.LWRFFeature object at 0x7fd60d439100>
```

Full logs below with debugging attached: [debug-lightwaverf-bje-20220413-2120.txt](https://github.com/bigbadblunt/homeassistant-lightwave2/files/8484462/debug-lightwaverf-bje-20220413-2120.txt)

My lights and radiators are all in `unavailable` state in HA.

Any thoughts?  Any further debugging I can do to help?

Thank you,
Jaco

**Comment by bigbadblunt** [comment]
Is this working through the app? The "'code': 404, 'message': 'dispatcher: destination not connected'" in the logs suggests a connection error (e.g. the link is not connected to the internet).

**Comment by pfinnigan** [comment]
The upgrade to v3.5.13 failed for me. App worked well, or as well as it always does. I went back to v3.5.10 and all worked fine in HA.

**Comment by bigbadblunt** [comment]
@pfinnigan can you provide logs please?

**Comment by pfinnigan** [comment]
Sorry for the delay I needed to get time to check this out. I have upgraded to v3.5.13 again, restarted HA and the log reports:

Error setting up entry (Imported from configuration.yaml) for lightwave2

From my HA config file the old lightwave config is still in there, but commented out as I am no longer using the config file.
```
# HACS integrations
#lightwave2:
#  username: {myuser}
#  password: !secret lightwave2_pw
```
The detailed log is:
```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/lightwave2/__init__.py:45
Integration: Lightwave v2 (Smart Series) custom component (documentation)
First occurred: 10:33:53 (1 occurrences)
Last logged: 10:33:53

Error setting up entry (Imported from configuration.yaml) for lightwave2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/lightwave2/__init__.py", line 45, in async_setup_entry
    await link.async_get_hierarchy()
  File "/usr/local/lib/python3.9/site-packages/lightwave2/lightwave2.py", line 584, in async_get_hierarchy
    await self.async_update_featureset_states()
  File "/usr/local/lib/python3.9/site-packages/lightwave2/lightwave2.py", line 633, in async_update_featureset_states
    if self.featuresets[featuresetid].features[featurename].id in req:
AttributeError: 'list' object has no attribute 'id'
```
All lighwave components are showing as unavailable. All the sockets/switches are version 1 devices and I also have the original (rubbish) thermostat. Nothing is working in HA they all work from the lightwaverf App. I have also downgraded to v3.5.10 again and everything started to work.

**Comment by bigbadblunt** [comment]
@pfinnigan your issue is the same as #68 - can you turn of use of the public API.

**Comment by bigbadblunt** [comment]
@bje any update on your issue?

**Comment by bigbadblunt** [comment]
@bje any update on your issue?

**Comment by bje** [comment]
> @bje any update on your issue?

All sorted my end.  It was indeed a connectivity issue 😊  Thank you for looking into this, and also for this plugin!
