### ISSUE TITLE
TRV's setting the temperature level 

### ISSUE THREAD

**Issue by AngloYorkshire** [bigbadblunt/homeassistant-lightwave2#70]
Hi,

Thanks for your great work but I was wondering if it would be possible to make it so you can set the temperature rather than the setting the percentage in an automation?

Thanks

Ideally provide output from homeassistant.log, preferably with additional logging enabled.

To enable additional logging, add the following to configuration.yaml

logger:
  default: warning
  logs:
    lightwave2.lightwave2: debug
    custom_components.lightwave2: debug

**Comment by bigbadblunt** [comment]
Hi, I don't understand the request. Setting target temperature should already be supported as per the screenshot below.

![image](https://user-images.githubusercontent.com/29158690/164885613-f5f338e1-00df-4349-86b4-a1fbb1b04f6a.png)

**Comment by AngloYorkshire** [comment]
It's ok - sorted thanks
