### ISSUE TITLE
Weird things( only way of describing it)

### ISSUE THREAD

**Issue by ste19m** [bigbadblunt/homeassistant-lightwave2#78]
This integration worked for me for around a week, now I find lights will randomly switch on whenever they feel like doing. Also I have automations set up for bathroom extraction to work from the switch triggering sonoff zig we switches but they no longer work and also the physical switches for certain lights ran the same way do nothing but will work from the app? Any ideas?

**Comment by bigbadblunt** [comment]
Can you turn on extra logging in the integration options and then send me a log file from when you have problems?

**Comment by ste19m** [comment]
hi, as soon as i turn on log extra debugging it works again, ill see how long it lasts usually its around an hour. ive deleted everything and re set up e
[lightwave debug.txt](https://github.com/bigbadblunt/homeassistant-lightwave2/files/8703336/lightwave.debug.txt)
verything with no change log files are attatched

**Comment by xela1** [comment]
> hi, as soon as i turn on log extra debugging it works again

This is exactly what I have, debug logging off it won't connect, debugging on it works fine

**Comment by ste19m** [comment]
Mine has stopped again it’s only anything that is attached via automation and on a physical press if I use the laptop/app it’s fine 

Kind Regards,
Steve Challinor

**Comment by bigbadblunt** [comment]
I don't completely understand your issue? Can you describe in more detail please what you want to happen and what is happening?

**Comment by ste19m** [comment]
I have a 3 gang switch that has my hallway lights wired straight to the switch and then the other 2 gangs have sonoff zigbee minis attached via automations to turn on and off. If I set up an automation for the switches to operate the zigbee minis they work for a vey short period of time on physical switch press and then stop but if you use home assistant and turn them on and off through that they will work. I also have my bathroom extractors via automation so if my light is on for a period of time it triggers the extraction, again this works for a short period and then stops but only on physical switch press. Hope this helps

Kind Regards,
Steve Challinor

**Comment by bigbadblunt** [comment]
How is my integration during in to this? Are you using it in the automation?

**Comment by xela1** [comment]
I assume he’s using the click events to trigger an automation. Which of course are stopping due to #69

**Comment by ste19m** [comment]
Yes it’s your integration to bring the Lightwave switches into ha. I’ve used the ha integration instead of yours and the switches work correctly but don’t integrate my trvs. So it has to be something in yours if that makes sense? Sorry I’m crap at explaining

Kind Regards,
Steve Challinor

**Comment by bigbadblunt** [comment]
Can you share the automation please? It does sound like it the same as #69

**Comment by bigbadblunt** [comment]
Ps you can use both integrations at the same time, and only use mine for trvs as a short term workaround

**Comment by ste19m** [comment]
I can do that no problems is there a way of removing your lights so they don’t re add? And I’m fine to do it this way for a 
Sorry I’m on my phone


Kind Regards,
Steve Challinor

**Comment by bigbadblunt** [comment]
You can disable them in ha
/config/devices/
Go into each device, click on the edit button (the pencil) and there should be a toggle to disable the device

Or you can just ignore them

**Comment by ste19m** [comment]
I would ignore them but Alexa doubles the devices up and stops listening to me

Kind Regards,
Steve Challinor

**Comment by bigbadblunt** [comment]
In the latest version there is an option to disable entities that are provided by homekit. This is in the configuration options.
