### ISSUE TITLE
Was working, now wont work at all.

### ISSUE THREAD

**Issue by MrLeeches** [bigbadblunt/homeassistant-lightwave2#80]
Set this up a few days ago and it was working fine. After a restart earlier it just will not come back up.

I have deleted both HA and HACS integrations but it doesnt seem to want to come back up
[LW2_log1.txt](https://github.com/bigbadblunt/homeassistant-lightwave2/files/8702795/LW2_log1.txt)
[LW2_log2.txt](https://github.com/bigbadblunt/homeassistant-lightwave2/files/8702796/LW2_log2.txt)
.

**Comment by astirling01** [comment]
I think Lightwave have been having issues. It's been down on my Alexa too. I switched from the public api and I've managed to reconnect.

**Comment by MrLeeches** [comment]
Yep, looks like Lightwave were having issues as it's now working flawlessly.

Thanks (and sorry!)
