### ISSUE TITLE
Turn on/off not recorded in History or log book

### ISSUE THREAD

**Issue by MikeLDPT** [bigbadblunt/homeassistant-lightwave2#82]
I have had several occasions when I've noticed that a light which is on should have been switched off by HA automation after a 10 minute limit.  On investigating why not, I find that the light is not recorded as 'On' in history and has no recent history in the log book.  I can turn the light on and off using HA and these events are logged in history and log book. Subsequent toggle on and off by the switch itself are not recorded in the logbook or history.
It seems I need to restart HA to get the switch actions to record in HA again.

**Comment by bigbadblunt** [comment]
This is the same as #69. See also the workaround in #77.

**Comment by bigbadblunt** [comment]
Closing as duplicate.
