### ISSUE TITLE
Deprecation warning in HASS log

### ISSUE THREAD

**Issue by uvjim** [bigbadblunt/homeassistant-lightwave2#83]
After upgrade to HASS 2022.6 the following warning appears in the log.

```
Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for lightwave2 using this method at custom_components/lightwave2/__init__.py, line 103: device_registry = await dr.async_get_registry(hass)
```

Running 3.5.1beta5 of the integration.

**Comment by incarvr6** [comment]
Same here.
`Logger: homeassistant.helpers.frame
Source: helpers/frame.py:103
First occurred: 12:44:10 (1 occurrences)
Last logged: 12:44:10

Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for lightwave2 using this method at custom_components/lightwave2/__init__.py, line 61: device_registry = await dr.async_get_registry(hass)`
