### ISSUE TITLE
Device Status not reflected in HA Dashboard 

### ISSUE THREAD

**Issue by bigdmo007** [bigbadblunt/homeassistant-lightwave2#93]
Switching lights on/off at the physical devices is not reflected in the HA light toggle button in my dashboard.

100% expect this to be MY issue, not this repository, but need to check/would like to fix

**Comment by bigbadblunt** [comment]
This is a duplicate of #69 

Short version, it is neither your fault, nor something I can fix. There are a couple of workarounds, or you could use homekit.

**Comment by bigdmo007** [comment]
Thanks for pointing me to the original post @bigbadblunt 

Keep up the great work!
