### ISSUE TITLE
Thermostat always shows as "Heating" in Home Assistant

### ISSUE THREAD

**Issue by SGXander** [bigbadblunt/homeassistant-lightwave2#95]
Not sure if this is a bug or not so maybe just confirming but I thought the thermostat would appear as on in heat mode but with "Off (Heat)" when not active. Now it seems to show in Home Assistant as "Heating (Heat)" for the duration of being on.

**Comment by bigbadblunt** [comment]
I've only just seen this one. I don't understand. Can you provide screenshots and describe the expected behaviour in more detail?

**Comment by bigbadblunt** [comment]
Any update on this one?

**Comment by SGXander** [comment]
Hey mate I've swapped it out for a shelly controlling the boiler from the wiring center now but the thermostat used to show mode: heat and then status heating as in whether it was passing through to the boiler or not but it stopped with the update above. Can't test now though so will close this.
