### ISSUE TITLE
Switching entities No longer visible in home-assistant 

### ISSUE THREAD

**Issue by mcevansw** [bigbadblunt/homeassistant-lightwave2#96]
Version 2022.10.5

unable to gather detail as the only entity i see is to turn the led off and on.

**Comment by bigbadblunt** [comment]
I can't reproduce this. Can you check your configuration - make sure "hide HomeKit entities" is not checked.

![image](https://user-images.githubusercontent.com/29158690/197322478-91cf0f95-8b79-449e-a8dc-37541946ca19.png)

If that doesn't work, please turn on additional logging and send me the logs.

**Comment by mcevansw** [comment]
There were not selected or hidden when I looked but I re-installed, and it is not working as expected. 
Thanks for the quick response
