### ISSUE TITLE
Lightwave click events not received when Homekit devices hidden

### ISSUE THREAD

**Issue by garysargentpersonal** [bigbadblunt/homeassistant-lightwave2#99]
When selecting the option to hide Homekit devices, the lightwave2.click event does not fire.

Homekit does not provide click events, so I'd expect the integration to provide these.

**Comment by bigbadblunt** [comment]
I've pushed a new beta release, please test. This should also address issues #100, #101, #102

**Comment by garysargentpersonal** [comment]
The events are now being received thanks. I'm having issues with some of the others - will comment on those so you are able to close this ticket.
